// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "edge_detector.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const int edge_detector::C_S_AXI_DATA_WIDTH = "100000";
const int edge_detector::C_S_AXI_WSTRB_WIDTH = "100";
const int edge_detector::C_S_AXI_ADDR_WIDTH = "100000";
const sc_logic edge_detector::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<24> edge_detector::ap_const_lv24_0 = "000000000000000000000000";
const sc_lv<3> edge_detector::ap_const_lv3_0 = "000";
const sc_lv<1> edge_detector::ap_const_lv1_0 = "0";
const sc_logic edge_detector::ap_const_logic_0 = sc_dt::Log_0;

edge_detector::edge_detector(sc_module_name name) : sc_module(name), mVcdFile(0) {
    edge_detector_AXILiteS_s_axi_U = new edge_detector_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>("edge_detector_AXILiteS_s_axi_U");
    edge_detector_AXILiteS_s_axi_U->AWVALID(s_axi_AXILiteS_AWVALID);
    edge_detector_AXILiteS_s_axi_U->AWREADY(s_axi_AXILiteS_AWREADY);
    edge_detector_AXILiteS_s_axi_U->AWADDR(s_axi_AXILiteS_AWADDR);
    edge_detector_AXILiteS_s_axi_U->WVALID(s_axi_AXILiteS_WVALID);
    edge_detector_AXILiteS_s_axi_U->WREADY(s_axi_AXILiteS_WREADY);
    edge_detector_AXILiteS_s_axi_U->WDATA(s_axi_AXILiteS_WDATA);
    edge_detector_AXILiteS_s_axi_U->WSTRB(s_axi_AXILiteS_WSTRB);
    edge_detector_AXILiteS_s_axi_U->ARVALID(s_axi_AXILiteS_ARVALID);
    edge_detector_AXILiteS_s_axi_U->ARREADY(s_axi_AXILiteS_ARREADY);
    edge_detector_AXILiteS_s_axi_U->ARADDR(s_axi_AXILiteS_ARADDR);
    edge_detector_AXILiteS_s_axi_U->RVALID(s_axi_AXILiteS_RVALID);
    edge_detector_AXILiteS_s_axi_U->RREADY(s_axi_AXILiteS_RREADY);
    edge_detector_AXILiteS_s_axi_U->RDATA(s_axi_AXILiteS_RDATA);
    edge_detector_AXILiteS_s_axi_U->RRESP(s_axi_AXILiteS_RRESP);
    edge_detector_AXILiteS_s_axi_U->BVALID(s_axi_AXILiteS_BVALID);
    edge_detector_AXILiteS_s_axi_U->BREADY(s_axi_AXILiteS_BREADY);
    edge_detector_AXILiteS_s_axi_U->BRESP(s_axi_AXILiteS_BRESP);
    edge_detector_AXILiteS_s_axi_U->ACLK(ap_clk);
    edge_detector_AXILiteS_s_axi_U->ARESET(ap_rst_n_inv);
    edge_detector_AXILiteS_s_axi_U->ACLK_EN(ap_var_for_const0);
    edge_detector_AXILiteS_s_axi_U->threshold(threshold);
    Block_proc232_U0 = new Block_proc232("Block_proc232_U0");
    Block_proc232_U0->ap_clk(ap_clk);
    Block_proc232_U0->ap_rst(ap_rst_n_inv);
    Block_proc232_U0->ap_start(Block_proc232_U0_ap_start);
    Block_proc232_U0->start_full_n(start_for_thresholding_U0_full_n);
    Block_proc232_U0->ap_done(Block_proc232_U0_ap_done);
    Block_proc232_U0->ap_continue(Block_proc232_U0_ap_continue);
    Block_proc232_U0->ap_idle(Block_proc232_U0_ap_idle);
    Block_proc232_U0->ap_ready(Block_proc232_U0_ap_ready);
    Block_proc232_U0->start_out(Block_proc232_U0_start_out);
    Block_proc232_U0->start_write(Block_proc232_U0_start_write);
    Block_proc232_U0->threshold(threshold);
    Block_proc232_U0->srcImg_rows_V_out_din(Block_proc232_U0_srcImg_rows_V_out_din);
    Block_proc232_U0->srcImg_rows_V_out_full_n(srcImg_rows_V_c_full_n);
    Block_proc232_U0->srcImg_rows_V_out_write(Block_proc232_U0_srcImg_rows_V_out_write);
    Block_proc232_U0->srcImg_cols_V_out_din(Block_proc232_U0_srcImg_cols_V_out_din);
    Block_proc232_U0->srcImg_cols_V_out_full_n(srcImg_cols_V_c_full_n);
    Block_proc232_U0->srcImg_cols_V_out_write(Block_proc232_U0_srcImg_cols_V_out_write);
    Block_proc232_U0->threshold_out_din(Block_proc232_U0_threshold_out_din);
    Block_proc232_U0->threshold_out_full_n(threshold_c_full_n);
    Block_proc232_U0->threshold_out_write(Block_proc232_U0_threshold_out_write);
    AXIvideo2Mat_U0 = new AXIvideo2Mat("AXIvideo2Mat_U0");
    AXIvideo2Mat_U0->ap_clk(ap_clk);
    AXIvideo2Mat_U0->ap_rst(ap_rst_n_inv);
    AXIvideo2Mat_U0->ap_start(AXIvideo2Mat_U0_ap_start);
    AXIvideo2Mat_U0->start_full_n(start_for_CvtColor_U0_full_n);
    AXIvideo2Mat_U0->ap_done(AXIvideo2Mat_U0_ap_done);
    AXIvideo2Mat_U0->ap_continue(AXIvideo2Mat_U0_ap_continue);
    AXIvideo2Mat_U0->ap_idle(AXIvideo2Mat_U0_ap_idle);
    AXIvideo2Mat_U0->ap_ready(AXIvideo2Mat_U0_ap_ready);
    AXIvideo2Mat_U0->start_out(AXIvideo2Mat_U0_start_out);
    AXIvideo2Mat_U0->start_write(AXIvideo2Mat_U0_start_write);
    AXIvideo2Mat_U0->src_TDATA(src_TDATA);
    AXIvideo2Mat_U0->src_TVALID(src_TVALID);
    AXIvideo2Mat_U0->src_TREADY(AXIvideo2Mat_U0_src_TREADY);
    AXIvideo2Mat_U0->src_TKEEP(src_TKEEP);
    AXIvideo2Mat_U0->src_TSTRB(src_TSTRB);
    AXIvideo2Mat_U0->src_TUSER(src_TUSER);
    AXIvideo2Mat_U0->src_TLAST(src_TLAST);
    AXIvideo2Mat_U0->src_TID(src_TID);
    AXIvideo2Mat_U0->src_TDEST(src_TDEST);
    AXIvideo2Mat_U0->img_rows_V_dout(srcImg_rows_V_c_dout);
    AXIvideo2Mat_U0->img_rows_V_empty_n(srcImg_rows_V_c_empty_n);
    AXIvideo2Mat_U0->img_rows_V_read(AXIvideo2Mat_U0_img_rows_V_read);
    AXIvideo2Mat_U0->img_cols_V_dout(srcImg_cols_V_c_dout);
    AXIvideo2Mat_U0->img_cols_V_empty_n(srcImg_cols_V_c_empty_n);
    AXIvideo2Mat_U0->img_cols_V_read(AXIvideo2Mat_U0_img_cols_V_read);
    AXIvideo2Mat_U0->img_data_stream_0_V_din(AXIvideo2Mat_U0_img_data_stream_0_V_din);
    AXIvideo2Mat_U0->img_data_stream_0_V_full_n(srcImg_data_stream_0_full_n);
    AXIvideo2Mat_U0->img_data_stream_0_V_write(AXIvideo2Mat_U0_img_data_stream_0_V_write);
    AXIvideo2Mat_U0->img_data_stream_1_V_din(AXIvideo2Mat_U0_img_data_stream_1_V_din);
    AXIvideo2Mat_U0->img_data_stream_1_V_full_n(srcImg_data_stream_1_full_n);
    AXIvideo2Mat_U0->img_data_stream_1_V_write(AXIvideo2Mat_U0_img_data_stream_1_V_write);
    AXIvideo2Mat_U0->img_data_stream_2_V_din(AXIvideo2Mat_U0_img_data_stream_2_V_din);
    AXIvideo2Mat_U0->img_data_stream_2_V_full_n(srcImg_data_stream_2_full_n);
    AXIvideo2Mat_U0->img_data_stream_2_V_write(AXIvideo2Mat_U0_img_data_stream_2_V_write);
    AXIvideo2Mat_U0->img_rows_V_out_din(AXIvideo2Mat_U0_img_rows_V_out_din);
    AXIvideo2Mat_U0->img_rows_V_out_full_n(srcImg_rows_V_c20_full_n);
    AXIvideo2Mat_U0->img_rows_V_out_write(AXIvideo2Mat_U0_img_rows_V_out_write);
    AXIvideo2Mat_U0->img_cols_V_out_din(AXIvideo2Mat_U0_img_cols_V_out_din);
    AXIvideo2Mat_U0->img_cols_V_out_full_n(srcImg_cols_V_c21_full_n);
    AXIvideo2Mat_U0->img_cols_V_out_write(AXIvideo2Mat_U0_img_cols_V_out_write);
    CvtColor_U0 = new CvtColor("CvtColor_U0");
    CvtColor_U0->ap_clk(ap_clk);
    CvtColor_U0->ap_rst(ap_rst_n_inv);
    CvtColor_U0->ap_start(CvtColor_U0_ap_start);
    CvtColor_U0->start_full_n(start_for_Duplicate_U0_full_n);
    CvtColor_U0->ap_done(CvtColor_U0_ap_done);
    CvtColor_U0->ap_continue(CvtColor_U0_ap_continue);
    CvtColor_U0->ap_idle(CvtColor_U0_ap_idle);
    CvtColor_U0->ap_ready(CvtColor_U0_ap_ready);
    CvtColor_U0->start_out(CvtColor_U0_start_out);
    CvtColor_U0->start_write(CvtColor_U0_start_write);
    CvtColor_U0->p_src_rows_V_dout(srcImg_rows_V_c20_dout);
    CvtColor_U0->p_src_rows_V_empty_n(srcImg_rows_V_c20_empty_n);
    CvtColor_U0->p_src_rows_V_read(CvtColor_U0_p_src_rows_V_read);
    CvtColor_U0->p_src_cols_V_dout(srcImg_cols_V_c21_dout);
    CvtColor_U0->p_src_cols_V_empty_n(srcImg_cols_V_c21_empty_n);
    CvtColor_U0->p_src_cols_V_read(CvtColor_U0_p_src_cols_V_read);
    CvtColor_U0->p_src_data_stream_0_V_dout(srcImg_data_stream_0_dout);
    CvtColor_U0->p_src_data_stream_0_V_empty_n(srcImg_data_stream_0_empty_n);
    CvtColor_U0->p_src_data_stream_0_V_read(CvtColor_U0_p_src_data_stream_0_V_read);
    CvtColor_U0->p_src_data_stream_1_V_dout(srcImg_data_stream_1_dout);
    CvtColor_U0->p_src_data_stream_1_V_empty_n(srcImg_data_stream_1_empty_n);
    CvtColor_U0->p_src_data_stream_1_V_read(CvtColor_U0_p_src_data_stream_1_V_read);
    CvtColor_U0->p_src_data_stream_2_V_dout(srcImg_data_stream_2_dout);
    CvtColor_U0->p_src_data_stream_2_V_empty_n(srcImg_data_stream_2_empty_n);
    CvtColor_U0->p_src_data_stream_2_V_read(CvtColor_U0_p_src_data_stream_2_V_read);
    CvtColor_U0->p_dst_data_stream_V_din(CvtColor_U0_p_dst_data_stream_V_din);
    CvtColor_U0->p_dst_data_stream_V_full_n(grayImg_data_stream_s_full_n);
    CvtColor_U0->p_dst_data_stream_V_write(CvtColor_U0_p_dst_data_stream_V_write);
    Duplicate_U0 = new Duplicate("Duplicate_U0");
    Duplicate_U0->ap_clk(ap_clk);
    Duplicate_U0->ap_rst(ap_rst_n_inv);
    Duplicate_U0->ap_start(Duplicate_U0_ap_start);
    Duplicate_U0->start_full_n(Duplicate_U0_start_full_n);
    Duplicate_U0->ap_done(Duplicate_U0_ap_done);
    Duplicate_U0->ap_continue(Duplicate_U0_ap_continue);
    Duplicate_U0->ap_idle(Duplicate_U0_ap_idle);
    Duplicate_U0->ap_ready(Duplicate_U0_ap_ready);
    Duplicate_U0->start_out(Duplicate_U0_start_out);
    Duplicate_U0->start_write(Duplicate_U0_start_write);
    Duplicate_U0->src_data_stream_V_dout(grayImg_data_stream_s_dout);
    Duplicate_U0->src_data_stream_V_empty_n(grayImg_data_stream_s_empty_n);
    Duplicate_U0->src_data_stream_V_read(Duplicate_U0_src_data_stream_V_read);
    Duplicate_U0->dst1_data_stream_V_din(Duplicate_U0_dst1_data_stream_V_din);
    Duplicate_U0->dst1_data_stream_V_full_n(split0_data_stream_0_full_n);
    Duplicate_U0->dst1_data_stream_V_write(Duplicate_U0_dst1_data_stream_V_write);
    Duplicate_U0->dst2_data_stream_V_din(Duplicate_U0_dst2_data_stream_V_din);
    Duplicate_U0->dst2_data_stream_V_full_n(split1_data_stream_0_full_n);
    Duplicate_U0->dst2_data_stream_V_write(Duplicate_U0_dst2_data_stream_V_write);
    Filter2D102_U0 = new Filter2D102("Filter2D102_U0");
    Filter2D102_U0->ap_clk(ap_clk);
    Filter2D102_U0->ap_rst(ap_rst_n_inv);
    Filter2D102_U0->ap_start(Filter2D102_U0_ap_start);
    Filter2D102_U0->start_full_n(start_for_AddWeighted_U0_full_n);
    Filter2D102_U0->ap_done(Filter2D102_U0_ap_done);
    Filter2D102_U0->ap_continue(Filter2D102_U0_ap_continue);
    Filter2D102_U0->ap_idle(Filter2D102_U0_ap_idle);
    Filter2D102_U0->ap_ready(Filter2D102_U0_ap_ready);
    Filter2D102_U0->start_out(Filter2D102_U0_start_out);
    Filter2D102_U0->start_write(Filter2D102_U0_start_write);
    Filter2D102_U0->p_src_data_stream_V_dout(split0_data_stream_0_dout);
    Filter2D102_U0->p_src_data_stream_V_empty_n(split0_data_stream_0_empty_n);
    Filter2D102_U0->p_src_data_stream_V_read(Filter2D102_U0_p_src_data_stream_V_read);
    Filter2D102_U0->p_dst_data_stream_V_din(Filter2D102_U0_p_dst_data_stream_V_din);
    Filter2D102_U0->p_dst_data_stream_V_full_n(sobelImg_x_data_stre_full_n);
    Filter2D102_U0->p_dst_data_stream_V_write(Filter2D102_U0_p_dst_data_stream_V_write);
    Filter2D_U0 = new Filter2D("Filter2D_U0");
    Filter2D_U0->ap_clk(ap_clk);
    Filter2D_U0->ap_rst(ap_rst_n_inv);
    Filter2D_U0->ap_start(Filter2D_U0_ap_start);
    Filter2D_U0->ap_done(Filter2D_U0_ap_done);
    Filter2D_U0->ap_continue(Filter2D_U0_ap_continue);
    Filter2D_U0->ap_idle(Filter2D_U0_ap_idle);
    Filter2D_U0->ap_ready(Filter2D_U0_ap_ready);
    Filter2D_U0->p_src_data_stream_V_dout(split1_data_stream_0_dout);
    Filter2D_U0->p_src_data_stream_V_empty_n(split1_data_stream_0_empty_n);
    Filter2D_U0->p_src_data_stream_V_read(Filter2D_U0_p_src_data_stream_V_read);
    Filter2D_U0->p_dst_data_stream_V_din(Filter2D_U0_p_dst_data_stream_V_din);
    Filter2D_U0->p_dst_data_stream_V_full_n(sobelImg_y_data_stre_full_n);
    Filter2D_U0->p_dst_data_stream_V_write(Filter2D_U0_p_dst_data_stream_V_write);
    AddWeighted_U0 = new AddWeighted("AddWeighted_U0");
    AddWeighted_U0->ap_clk(ap_clk);
    AddWeighted_U0->ap_rst(ap_rst_n_inv);
    AddWeighted_U0->ap_start(AddWeighted_U0_ap_start);
    AddWeighted_U0->ap_done(AddWeighted_U0_ap_done);
    AddWeighted_U0->ap_continue(AddWeighted_U0_ap_continue);
    AddWeighted_U0->ap_idle(AddWeighted_U0_ap_idle);
    AddWeighted_U0->ap_ready(AddWeighted_U0_ap_ready);
    AddWeighted_U0->src1_data_stream_V_dout(sobelImg_x_data_stre_dout);
    AddWeighted_U0->src1_data_stream_V_empty_n(sobelImg_x_data_stre_empty_n);
    AddWeighted_U0->src1_data_stream_V_read(AddWeighted_U0_src1_data_stream_V_read);
    AddWeighted_U0->src2_data_stream_V_dout(sobelImg_y_data_stre_dout);
    AddWeighted_U0->src2_data_stream_V_empty_n(sobelImg_y_data_stre_empty_n);
    AddWeighted_U0->src2_data_stream_V_read(AddWeighted_U0_src2_data_stream_V_read);
    AddWeighted_U0->dst_data_stream_V_din(AddWeighted_U0_dst_data_stream_V_din);
    AddWeighted_U0->dst_data_stream_V_full_n(sobelImg_data_stream_full_n);
    AddWeighted_U0->dst_data_stream_V_write(AddWeighted_U0_dst_data_stream_V_write);
    thresholding_U0 = new thresholding("thresholding_U0");
    thresholding_U0->ap_clk(ap_clk);
    thresholding_U0->ap_rst(ap_rst_n_inv);
    thresholding_U0->ap_start(thresholding_U0_ap_start);
    thresholding_U0->start_full_n(start_for_CvtColor_1_U0_full_n);
    thresholding_U0->ap_done(thresholding_U0_ap_done);
    thresholding_U0->ap_continue(thresholding_U0_ap_continue);
    thresholding_U0->ap_idle(thresholding_U0_ap_idle);
    thresholding_U0->ap_ready(thresholding_U0_ap_ready);
    thresholding_U0->start_out(thresholding_U0_start_out);
    thresholding_U0->start_write(thresholding_U0_start_write);
    thresholding_U0->dst_data_stream_V_din(thresholding_U0_dst_data_stream_V_din);
    thresholding_U0->dst_data_stream_V_full_n(thresholdImg_data_st_full_n);
    thresholding_U0->dst_data_stream_V_write(thresholding_U0_dst_data_stream_V_write);
    thresholding_U0->src_data_stream_V_dout(sobelImg_data_stream_dout);
    thresholding_U0->src_data_stream_V_empty_n(sobelImg_data_stream_empty_n);
    thresholding_U0->src_data_stream_V_read(thresholding_U0_src_data_stream_V_read);
    thresholding_U0->threshold_dout(threshold_c_dout);
    thresholding_U0->threshold_empty_n(threshold_c_empty_n);
    thresholding_U0->threshold_read(thresholding_U0_threshold_read);
    CvtColor_1_U0 = new CvtColor_1("CvtColor_1_U0");
    CvtColor_1_U0->ap_clk(ap_clk);
    CvtColor_1_U0->ap_rst(ap_rst_n_inv);
    CvtColor_1_U0->ap_start(CvtColor_1_U0_ap_start);
    CvtColor_1_U0->start_full_n(start_for_Mat2AXIvideo_U0_full_n);
    CvtColor_1_U0->ap_done(CvtColor_1_U0_ap_done);
    CvtColor_1_U0->ap_continue(CvtColor_1_U0_ap_continue);
    CvtColor_1_U0->ap_idle(CvtColor_1_U0_ap_idle);
    CvtColor_1_U0->ap_ready(CvtColor_1_U0_ap_ready);
    CvtColor_1_U0->start_out(CvtColor_1_U0_start_out);
    CvtColor_1_U0->start_write(CvtColor_1_U0_start_write);
    CvtColor_1_U0->p_src_data_stream_V_dout(thresholdImg_data_st_dout);
    CvtColor_1_U0->p_src_data_stream_V_empty_n(thresholdImg_data_st_empty_n);
    CvtColor_1_U0->p_src_data_stream_V_read(CvtColor_1_U0_p_src_data_stream_V_read);
    CvtColor_1_U0->p_dst_data_stream_0_V_din(CvtColor_1_U0_p_dst_data_stream_0_V_din);
    CvtColor_1_U0->p_dst_data_stream_0_V_full_n(rgbSobel_data_stream_full_n);
    CvtColor_1_U0->p_dst_data_stream_0_V_write(CvtColor_1_U0_p_dst_data_stream_0_V_write);
    CvtColor_1_U0->p_dst_data_stream_1_V_din(CvtColor_1_U0_p_dst_data_stream_1_V_din);
    CvtColor_1_U0->p_dst_data_stream_1_V_full_n(rgbSobel_data_stream_1_full_n);
    CvtColor_1_U0->p_dst_data_stream_1_V_write(CvtColor_1_U0_p_dst_data_stream_1_V_write);
    CvtColor_1_U0->p_dst_data_stream_2_V_din(CvtColor_1_U0_p_dst_data_stream_2_V_din);
    CvtColor_1_U0->p_dst_data_stream_2_V_full_n(rgbSobel_data_stream_2_full_n);
    CvtColor_1_U0->p_dst_data_stream_2_V_write(CvtColor_1_U0_p_dst_data_stream_2_V_write);
    Mat2AXIvideo_U0 = new Mat2AXIvideo("Mat2AXIvideo_U0");
    Mat2AXIvideo_U0->ap_clk(ap_clk);
    Mat2AXIvideo_U0->ap_rst(ap_rst_n_inv);
    Mat2AXIvideo_U0->ap_start(Mat2AXIvideo_U0_ap_start);
    Mat2AXIvideo_U0->ap_done(Mat2AXIvideo_U0_ap_done);
    Mat2AXIvideo_U0->ap_continue(Mat2AXIvideo_U0_ap_continue);
    Mat2AXIvideo_U0->ap_idle(Mat2AXIvideo_U0_ap_idle);
    Mat2AXIvideo_U0->ap_ready(Mat2AXIvideo_U0_ap_ready);
    Mat2AXIvideo_U0->img_data_stream_0_V_dout(rgbSobel_data_stream_dout);
    Mat2AXIvideo_U0->img_data_stream_0_V_empty_n(rgbSobel_data_stream_empty_n);
    Mat2AXIvideo_U0->img_data_stream_0_V_read(Mat2AXIvideo_U0_img_data_stream_0_V_read);
    Mat2AXIvideo_U0->img_data_stream_1_V_dout(rgbSobel_data_stream_1_dout);
    Mat2AXIvideo_U0->img_data_stream_1_V_empty_n(rgbSobel_data_stream_1_empty_n);
    Mat2AXIvideo_U0->img_data_stream_1_V_read(Mat2AXIvideo_U0_img_data_stream_1_V_read);
    Mat2AXIvideo_U0->img_data_stream_2_V_dout(rgbSobel_data_stream_2_dout);
    Mat2AXIvideo_U0->img_data_stream_2_V_empty_n(rgbSobel_data_stream_2_empty_n);
    Mat2AXIvideo_U0->img_data_stream_2_V_read(Mat2AXIvideo_U0_img_data_stream_2_V_read);
    Mat2AXIvideo_U0->dst_TDATA(Mat2AXIvideo_U0_dst_TDATA);
    Mat2AXIvideo_U0->dst_TVALID(Mat2AXIvideo_U0_dst_TVALID);
    Mat2AXIvideo_U0->dst_TREADY(dst_TREADY);
    Mat2AXIvideo_U0->dst_TKEEP(Mat2AXIvideo_U0_dst_TKEEP);
    Mat2AXIvideo_U0->dst_TSTRB(Mat2AXIvideo_U0_dst_TSTRB);
    Mat2AXIvideo_U0->dst_TUSER(Mat2AXIvideo_U0_dst_TUSER);
    Mat2AXIvideo_U0->dst_TLAST(Mat2AXIvideo_U0_dst_TLAST);
    Mat2AXIvideo_U0->dst_TID(Mat2AXIvideo_U0_dst_TID);
    Mat2AXIvideo_U0->dst_TDEST(Mat2AXIvideo_U0_dst_TDEST);
    srcImg_rows_V_c_U = new fifo_w12_d2_A("srcImg_rows_V_c_U");
    srcImg_rows_V_c_U->clk(ap_clk);
    srcImg_rows_V_c_U->reset(ap_rst_n_inv);
    srcImg_rows_V_c_U->if_read_ce(ap_var_for_const0);
    srcImg_rows_V_c_U->if_write_ce(ap_var_for_const0);
    srcImg_rows_V_c_U->if_din(Block_proc232_U0_srcImg_rows_V_out_din);
    srcImg_rows_V_c_U->if_full_n(srcImg_rows_V_c_full_n);
    srcImg_rows_V_c_U->if_write(Block_proc232_U0_srcImg_rows_V_out_write);
    srcImg_rows_V_c_U->if_dout(srcImg_rows_V_c_dout);
    srcImg_rows_V_c_U->if_empty_n(srcImg_rows_V_c_empty_n);
    srcImg_rows_V_c_U->if_read(AXIvideo2Mat_U0_img_rows_V_read);
    srcImg_cols_V_c_U = new fifo_w12_d2_A("srcImg_cols_V_c_U");
    srcImg_cols_V_c_U->clk(ap_clk);
    srcImg_cols_V_c_U->reset(ap_rst_n_inv);
    srcImg_cols_V_c_U->if_read_ce(ap_var_for_const0);
    srcImg_cols_V_c_U->if_write_ce(ap_var_for_const0);
    srcImg_cols_V_c_U->if_din(Block_proc232_U0_srcImg_cols_V_out_din);
    srcImg_cols_V_c_U->if_full_n(srcImg_cols_V_c_full_n);
    srcImg_cols_V_c_U->if_write(Block_proc232_U0_srcImg_cols_V_out_write);
    srcImg_cols_V_c_U->if_dout(srcImg_cols_V_c_dout);
    srcImg_cols_V_c_U->if_empty_n(srcImg_cols_V_c_empty_n);
    srcImg_cols_V_c_U->if_read(AXIvideo2Mat_U0_img_cols_V_read);
    threshold_c_U = new fifo_w8_d7_A("threshold_c_U");
    threshold_c_U->clk(ap_clk);
    threshold_c_U->reset(ap_rst_n_inv);
    threshold_c_U->if_read_ce(ap_var_for_const0);
    threshold_c_U->if_write_ce(ap_var_for_const0);
    threshold_c_U->if_din(Block_proc232_U0_threshold_out_din);
    threshold_c_U->if_full_n(threshold_c_full_n);
    threshold_c_U->if_write(Block_proc232_U0_threshold_out_write);
    threshold_c_U->if_dout(threshold_c_dout);
    threshold_c_U->if_empty_n(threshold_c_empty_n);
    threshold_c_U->if_read(thresholding_U0_threshold_read);
    srcImg_data_stream_0_U = new fifo_w8_d2_A("srcImg_data_stream_0_U");
    srcImg_data_stream_0_U->clk(ap_clk);
    srcImg_data_stream_0_U->reset(ap_rst_n_inv);
    srcImg_data_stream_0_U->if_read_ce(ap_var_for_const0);
    srcImg_data_stream_0_U->if_write_ce(ap_var_for_const0);
    srcImg_data_stream_0_U->if_din(AXIvideo2Mat_U0_img_data_stream_0_V_din);
    srcImg_data_stream_0_U->if_full_n(srcImg_data_stream_0_full_n);
    srcImg_data_stream_0_U->if_write(AXIvideo2Mat_U0_img_data_stream_0_V_write);
    srcImg_data_stream_0_U->if_dout(srcImg_data_stream_0_dout);
    srcImg_data_stream_0_U->if_empty_n(srcImg_data_stream_0_empty_n);
    srcImg_data_stream_0_U->if_read(CvtColor_U0_p_src_data_stream_0_V_read);
    srcImg_data_stream_1_U = new fifo_w8_d2_A("srcImg_data_stream_1_U");
    srcImg_data_stream_1_U->clk(ap_clk);
    srcImg_data_stream_1_U->reset(ap_rst_n_inv);
    srcImg_data_stream_1_U->if_read_ce(ap_var_for_const0);
    srcImg_data_stream_1_U->if_write_ce(ap_var_for_const0);
    srcImg_data_stream_1_U->if_din(AXIvideo2Mat_U0_img_data_stream_1_V_din);
    srcImg_data_stream_1_U->if_full_n(srcImg_data_stream_1_full_n);
    srcImg_data_stream_1_U->if_write(AXIvideo2Mat_U0_img_data_stream_1_V_write);
    srcImg_data_stream_1_U->if_dout(srcImg_data_stream_1_dout);
    srcImg_data_stream_1_U->if_empty_n(srcImg_data_stream_1_empty_n);
    srcImg_data_stream_1_U->if_read(CvtColor_U0_p_src_data_stream_1_V_read);
    srcImg_data_stream_2_U = new fifo_w8_d2_A("srcImg_data_stream_2_U");
    srcImg_data_stream_2_U->clk(ap_clk);
    srcImg_data_stream_2_U->reset(ap_rst_n_inv);
    srcImg_data_stream_2_U->if_read_ce(ap_var_for_const0);
    srcImg_data_stream_2_U->if_write_ce(ap_var_for_const0);
    srcImg_data_stream_2_U->if_din(AXIvideo2Mat_U0_img_data_stream_2_V_din);
    srcImg_data_stream_2_U->if_full_n(srcImg_data_stream_2_full_n);
    srcImg_data_stream_2_U->if_write(AXIvideo2Mat_U0_img_data_stream_2_V_write);
    srcImg_data_stream_2_U->if_dout(srcImg_data_stream_2_dout);
    srcImg_data_stream_2_U->if_empty_n(srcImg_data_stream_2_empty_n);
    srcImg_data_stream_2_U->if_read(CvtColor_U0_p_src_data_stream_2_V_read);
    srcImg_rows_V_c20_U = new fifo_w12_d2_A("srcImg_rows_V_c20_U");
    srcImg_rows_V_c20_U->clk(ap_clk);
    srcImg_rows_V_c20_U->reset(ap_rst_n_inv);
    srcImg_rows_V_c20_U->if_read_ce(ap_var_for_const0);
    srcImg_rows_V_c20_U->if_write_ce(ap_var_for_const0);
    srcImg_rows_V_c20_U->if_din(AXIvideo2Mat_U0_img_rows_V_out_din);
    srcImg_rows_V_c20_U->if_full_n(srcImg_rows_V_c20_full_n);
    srcImg_rows_V_c20_U->if_write(AXIvideo2Mat_U0_img_rows_V_out_write);
    srcImg_rows_V_c20_U->if_dout(srcImg_rows_V_c20_dout);
    srcImg_rows_V_c20_U->if_empty_n(srcImg_rows_V_c20_empty_n);
    srcImg_rows_V_c20_U->if_read(CvtColor_U0_p_src_rows_V_read);
    srcImg_cols_V_c21_U = new fifo_w12_d2_A("srcImg_cols_V_c21_U");
    srcImg_cols_V_c21_U->clk(ap_clk);
    srcImg_cols_V_c21_U->reset(ap_rst_n_inv);
    srcImg_cols_V_c21_U->if_read_ce(ap_var_for_const0);
    srcImg_cols_V_c21_U->if_write_ce(ap_var_for_const0);
    srcImg_cols_V_c21_U->if_din(AXIvideo2Mat_U0_img_cols_V_out_din);
    srcImg_cols_V_c21_U->if_full_n(srcImg_cols_V_c21_full_n);
    srcImg_cols_V_c21_U->if_write(AXIvideo2Mat_U0_img_cols_V_out_write);
    srcImg_cols_V_c21_U->if_dout(srcImg_cols_V_c21_dout);
    srcImg_cols_V_c21_U->if_empty_n(srcImg_cols_V_c21_empty_n);
    srcImg_cols_V_c21_U->if_read(CvtColor_U0_p_src_cols_V_read);
    grayImg_data_stream_s_U = new fifo_w8_d2_A("grayImg_data_stream_s_U");
    grayImg_data_stream_s_U->clk(ap_clk);
    grayImg_data_stream_s_U->reset(ap_rst_n_inv);
    grayImg_data_stream_s_U->if_read_ce(ap_var_for_const0);
    grayImg_data_stream_s_U->if_write_ce(ap_var_for_const0);
    grayImg_data_stream_s_U->if_din(CvtColor_U0_p_dst_data_stream_V_din);
    grayImg_data_stream_s_U->if_full_n(grayImg_data_stream_s_full_n);
    grayImg_data_stream_s_U->if_write(CvtColor_U0_p_dst_data_stream_V_write);
    grayImg_data_stream_s_U->if_dout(grayImg_data_stream_s_dout);
    grayImg_data_stream_s_U->if_empty_n(grayImg_data_stream_s_empty_n);
    grayImg_data_stream_s_U->if_read(Duplicate_U0_src_data_stream_V_read);
    split0_data_stream_0_U = new fifo_w8_d2_A("split0_data_stream_0_U");
    split0_data_stream_0_U->clk(ap_clk);
    split0_data_stream_0_U->reset(ap_rst_n_inv);
    split0_data_stream_0_U->if_read_ce(ap_var_for_const0);
    split0_data_stream_0_U->if_write_ce(ap_var_for_const0);
    split0_data_stream_0_U->if_din(Duplicate_U0_dst1_data_stream_V_din);
    split0_data_stream_0_U->if_full_n(split0_data_stream_0_full_n);
    split0_data_stream_0_U->if_write(Duplicate_U0_dst1_data_stream_V_write);
    split0_data_stream_0_U->if_dout(split0_data_stream_0_dout);
    split0_data_stream_0_U->if_empty_n(split0_data_stream_0_empty_n);
    split0_data_stream_0_U->if_read(Filter2D102_U0_p_src_data_stream_V_read);
    split1_data_stream_0_U = new fifo_w8_d2_A("split1_data_stream_0_U");
    split1_data_stream_0_U->clk(ap_clk);
    split1_data_stream_0_U->reset(ap_rst_n_inv);
    split1_data_stream_0_U->if_read_ce(ap_var_for_const0);
    split1_data_stream_0_U->if_write_ce(ap_var_for_const0);
    split1_data_stream_0_U->if_din(Duplicate_U0_dst2_data_stream_V_din);
    split1_data_stream_0_U->if_full_n(split1_data_stream_0_full_n);
    split1_data_stream_0_U->if_write(Duplicate_U0_dst2_data_stream_V_write);
    split1_data_stream_0_U->if_dout(split1_data_stream_0_dout);
    split1_data_stream_0_U->if_empty_n(split1_data_stream_0_empty_n);
    split1_data_stream_0_U->if_read(Filter2D_U0_p_src_data_stream_V_read);
    sobelImg_x_data_stre_U = new fifo_w8_d2_A("sobelImg_x_data_stre_U");
    sobelImg_x_data_stre_U->clk(ap_clk);
    sobelImg_x_data_stre_U->reset(ap_rst_n_inv);
    sobelImg_x_data_stre_U->if_read_ce(ap_var_for_const0);
    sobelImg_x_data_stre_U->if_write_ce(ap_var_for_const0);
    sobelImg_x_data_stre_U->if_din(Filter2D102_U0_p_dst_data_stream_V_din);
    sobelImg_x_data_stre_U->if_full_n(sobelImg_x_data_stre_full_n);
    sobelImg_x_data_stre_U->if_write(Filter2D102_U0_p_dst_data_stream_V_write);
    sobelImg_x_data_stre_U->if_dout(sobelImg_x_data_stre_dout);
    sobelImg_x_data_stre_U->if_empty_n(sobelImg_x_data_stre_empty_n);
    sobelImg_x_data_stre_U->if_read(AddWeighted_U0_src1_data_stream_V_read);
    sobelImg_y_data_stre_U = new fifo_w8_d2_A("sobelImg_y_data_stre_U");
    sobelImg_y_data_stre_U->clk(ap_clk);
    sobelImg_y_data_stre_U->reset(ap_rst_n_inv);
    sobelImg_y_data_stre_U->if_read_ce(ap_var_for_const0);
    sobelImg_y_data_stre_U->if_write_ce(ap_var_for_const0);
    sobelImg_y_data_stre_U->if_din(Filter2D_U0_p_dst_data_stream_V_din);
    sobelImg_y_data_stre_U->if_full_n(sobelImg_y_data_stre_full_n);
    sobelImg_y_data_stre_U->if_write(Filter2D_U0_p_dst_data_stream_V_write);
    sobelImg_y_data_stre_U->if_dout(sobelImg_y_data_stre_dout);
    sobelImg_y_data_stre_U->if_empty_n(sobelImg_y_data_stre_empty_n);
    sobelImg_y_data_stre_U->if_read(AddWeighted_U0_src2_data_stream_V_read);
    sobelImg_data_stream_U = new fifo_w8_d2_A("sobelImg_data_stream_U");
    sobelImg_data_stream_U->clk(ap_clk);
    sobelImg_data_stream_U->reset(ap_rst_n_inv);
    sobelImg_data_stream_U->if_read_ce(ap_var_for_const0);
    sobelImg_data_stream_U->if_write_ce(ap_var_for_const0);
    sobelImg_data_stream_U->if_din(AddWeighted_U0_dst_data_stream_V_din);
    sobelImg_data_stream_U->if_full_n(sobelImg_data_stream_full_n);
    sobelImg_data_stream_U->if_write(AddWeighted_U0_dst_data_stream_V_write);
    sobelImg_data_stream_U->if_dout(sobelImg_data_stream_dout);
    sobelImg_data_stream_U->if_empty_n(sobelImg_data_stream_empty_n);
    sobelImg_data_stream_U->if_read(thresholding_U0_src_data_stream_V_read);
    thresholdImg_data_st_U = new fifo_w8_d2_A("thresholdImg_data_st_U");
    thresholdImg_data_st_U->clk(ap_clk);
    thresholdImg_data_st_U->reset(ap_rst_n_inv);
    thresholdImg_data_st_U->if_read_ce(ap_var_for_const0);
    thresholdImg_data_st_U->if_write_ce(ap_var_for_const0);
    thresholdImg_data_st_U->if_din(thresholding_U0_dst_data_stream_V_din);
    thresholdImg_data_st_U->if_full_n(thresholdImg_data_st_full_n);
    thresholdImg_data_st_U->if_write(thresholding_U0_dst_data_stream_V_write);
    thresholdImg_data_st_U->if_dout(thresholdImg_data_st_dout);
    thresholdImg_data_st_U->if_empty_n(thresholdImg_data_st_empty_n);
    thresholdImg_data_st_U->if_read(CvtColor_1_U0_p_src_data_stream_V_read);
    rgbSobel_data_stream_U = new fifo_w8_d2_A("rgbSobel_data_stream_U");
    rgbSobel_data_stream_U->clk(ap_clk);
    rgbSobel_data_stream_U->reset(ap_rst_n_inv);
    rgbSobel_data_stream_U->if_read_ce(ap_var_for_const0);
    rgbSobel_data_stream_U->if_write_ce(ap_var_for_const0);
    rgbSobel_data_stream_U->if_din(CvtColor_1_U0_p_dst_data_stream_0_V_din);
    rgbSobel_data_stream_U->if_full_n(rgbSobel_data_stream_full_n);
    rgbSobel_data_stream_U->if_write(CvtColor_1_U0_p_dst_data_stream_0_V_write);
    rgbSobel_data_stream_U->if_dout(rgbSobel_data_stream_dout);
    rgbSobel_data_stream_U->if_empty_n(rgbSobel_data_stream_empty_n);
    rgbSobel_data_stream_U->if_read(Mat2AXIvideo_U0_img_data_stream_0_V_read);
    rgbSobel_data_stream_1_U = new fifo_w8_d2_A("rgbSobel_data_stream_1_U");
    rgbSobel_data_stream_1_U->clk(ap_clk);
    rgbSobel_data_stream_1_U->reset(ap_rst_n_inv);
    rgbSobel_data_stream_1_U->if_read_ce(ap_var_for_const0);
    rgbSobel_data_stream_1_U->if_write_ce(ap_var_for_const0);
    rgbSobel_data_stream_1_U->if_din(CvtColor_1_U0_p_dst_data_stream_1_V_din);
    rgbSobel_data_stream_1_U->if_full_n(rgbSobel_data_stream_1_full_n);
    rgbSobel_data_stream_1_U->if_write(CvtColor_1_U0_p_dst_data_stream_1_V_write);
    rgbSobel_data_stream_1_U->if_dout(rgbSobel_data_stream_1_dout);
    rgbSobel_data_stream_1_U->if_empty_n(rgbSobel_data_stream_1_empty_n);
    rgbSobel_data_stream_1_U->if_read(Mat2AXIvideo_U0_img_data_stream_1_V_read);
    rgbSobel_data_stream_2_U = new fifo_w8_d2_A("rgbSobel_data_stream_2_U");
    rgbSobel_data_stream_2_U->clk(ap_clk);
    rgbSobel_data_stream_2_U->reset(ap_rst_n_inv);
    rgbSobel_data_stream_2_U->if_read_ce(ap_var_for_const0);
    rgbSobel_data_stream_2_U->if_write_ce(ap_var_for_const0);
    rgbSobel_data_stream_2_U->if_din(CvtColor_1_U0_p_dst_data_stream_2_V_din);
    rgbSobel_data_stream_2_U->if_full_n(rgbSobel_data_stream_2_full_n);
    rgbSobel_data_stream_2_U->if_write(CvtColor_1_U0_p_dst_data_stream_2_V_write);
    rgbSobel_data_stream_2_U->if_dout(rgbSobel_data_stream_2_dout);
    rgbSobel_data_stream_2_U->if_empty_n(rgbSobel_data_stream_2_empty_n);
    rgbSobel_data_stream_2_U->if_read(Mat2AXIvideo_U0_img_data_stream_2_V_read);
    start_for_threshopcA_U = new start_for_threshopcA("start_for_threshopcA_U");
    start_for_threshopcA_U->clk(ap_clk);
    start_for_threshopcA_U->reset(ap_rst_n_inv);
    start_for_threshopcA_U->if_read_ce(ap_var_for_const0);
    start_for_threshopcA_U->if_write_ce(ap_var_for_const0);
    start_for_threshopcA_U->if_din(start_for_thresholding_U0_din);
    start_for_threshopcA_U->if_full_n(start_for_thresholding_U0_full_n);
    start_for_threshopcA_U->if_write(Block_proc232_U0_start_write);
    start_for_threshopcA_U->if_dout(start_for_thresholding_U0_dout);
    start_for_threshopcA_U->if_empty_n(start_for_thresholding_U0_empty_n);
    start_for_threshopcA_U->if_read(thresholding_U0_ap_ready);
    start_for_CvtColoqcK_U = new start_for_CvtColoqcK("start_for_CvtColoqcK_U");
    start_for_CvtColoqcK_U->clk(ap_clk);
    start_for_CvtColoqcK_U->reset(ap_rst_n_inv);
    start_for_CvtColoqcK_U->if_read_ce(ap_var_for_const0);
    start_for_CvtColoqcK_U->if_write_ce(ap_var_for_const0);
    start_for_CvtColoqcK_U->if_din(start_for_CvtColor_U0_din);
    start_for_CvtColoqcK_U->if_full_n(start_for_CvtColor_U0_full_n);
    start_for_CvtColoqcK_U->if_write(AXIvideo2Mat_U0_start_write);
    start_for_CvtColoqcK_U->if_dout(start_for_CvtColor_U0_dout);
    start_for_CvtColoqcK_U->if_empty_n(start_for_CvtColor_U0_empty_n);
    start_for_CvtColoqcK_U->if_read(CvtColor_U0_ap_ready);
    start_for_DuplicarcU_U = new start_for_DuplicarcU("start_for_DuplicarcU_U");
    start_for_DuplicarcU_U->clk(ap_clk);
    start_for_DuplicarcU_U->reset(ap_rst_n_inv);
    start_for_DuplicarcU_U->if_read_ce(ap_var_for_const0);
    start_for_DuplicarcU_U->if_write_ce(ap_var_for_const0);
    start_for_DuplicarcU_U->if_din(start_for_Duplicate_U0_din);
    start_for_DuplicarcU_U->if_full_n(start_for_Duplicate_U0_full_n);
    start_for_DuplicarcU_U->if_write(CvtColor_U0_start_write);
    start_for_DuplicarcU_U->if_dout(start_for_Duplicate_U0_dout);
    start_for_DuplicarcU_U->if_empty_n(start_for_Duplicate_U0_empty_n);
    start_for_DuplicarcU_U->if_read(Duplicate_U0_ap_ready);
    start_for_Filter2sc4_U = new start_for_Filter2sc4("start_for_Filter2sc4_U");
    start_for_Filter2sc4_U->clk(ap_clk);
    start_for_Filter2sc4_U->reset(ap_rst_n_inv);
    start_for_Filter2sc4_U->if_read_ce(ap_var_for_const0);
    start_for_Filter2sc4_U->if_write_ce(ap_var_for_const0);
    start_for_Filter2sc4_U->if_din(start_for_Filter2D102_U0_din);
    start_for_Filter2sc4_U->if_full_n(start_for_Filter2D102_U0_full_n);
    start_for_Filter2sc4_U->if_write(Duplicate_U0_start_write);
    start_for_Filter2sc4_U->if_dout(start_for_Filter2D102_U0_dout);
    start_for_Filter2sc4_U->if_empty_n(start_for_Filter2D102_U0_empty_n);
    start_for_Filter2sc4_U->if_read(Filter2D102_U0_ap_ready);
    start_for_Filter2tde_U = new start_for_Filter2tde("start_for_Filter2tde_U");
    start_for_Filter2tde_U->clk(ap_clk);
    start_for_Filter2tde_U->reset(ap_rst_n_inv);
    start_for_Filter2tde_U->if_read_ce(ap_var_for_const0);
    start_for_Filter2tde_U->if_write_ce(ap_var_for_const0);
    start_for_Filter2tde_U->if_din(start_for_Filter2D_U0_din);
    start_for_Filter2tde_U->if_full_n(start_for_Filter2D_U0_full_n);
    start_for_Filter2tde_U->if_write(Duplicate_U0_start_write);
    start_for_Filter2tde_U->if_dout(start_for_Filter2D_U0_dout);
    start_for_Filter2tde_U->if_empty_n(start_for_Filter2D_U0_empty_n);
    start_for_Filter2tde_U->if_read(Filter2D_U0_ap_ready);
    start_for_AddWeigudo_U = new start_for_AddWeigudo("start_for_AddWeigudo_U");
    start_for_AddWeigudo_U->clk(ap_clk);
    start_for_AddWeigudo_U->reset(ap_rst_n_inv);
    start_for_AddWeigudo_U->if_read_ce(ap_var_for_const0);
    start_for_AddWeigudo_U->if_write_ce(ap_var_for_const0);
    start_for_AddWeigudo_U->if_din(start_for_AddWeighted_U0_din);
    start_for_AddWeigudo_U->if_full_n(start_for_AddWeighted_U0_full_n);
    start_for_AddWeigudo_U->if_write(Filter2D102_U0_start_write);
    start_for_AddWeigudo_U->if_dout(start_for_AddWeighted_U0_dout);
    start_for_AddWeigudo_U->if_empty_n(start_for_AddWeighted_U0_empty_n);
    start_for_AddWeigudo_U->if_read(AddWeighted_U0_ap_ready);
    start_for_CvtColovdy_U = new start_for_CvtColovdy("start_for_CvtColovdy_U");
    start_for_CvtColovdy_U->clk(ap_clk);
    start_for_CvtColovdy_U->reset(ap_rst_n_inv);
    start_for_CvtColovdy_U->if_read_ce(ap_var_for_const0);
    start_for_CvtColovdy_U->if_write_ce(ap_var_for_const0);
    start_for_CvtColovdy_U->if_din(start_for_CvtColor_1_U0_din);
    start_for_CvtColovdy_U->if_full_n(start_for_CvtColor_1_U0_full_n);
    start_for_CvtColovdy_U->if_write(thresholding_U0_start_write);
    start_for_CvtColovdy_U->if_dout(start_for_CvtColor_1_U0_dout);
    start_for_CvtColovdy_U->if_empty_n(start_for_CvtColor_1_U0_empty_n);
    start_for_CvtColovdy_U->if_read(CvtColor_1_U0_ap_ready);
    start_for_Mat2AXIwdI_U = new start_for_Mat2AXIwdI("start_for_Mat2AXIwdI_U");
    start_for_Mat2AXIwdI_U->clk(ap_clk);
    start_for_Mat2AXIwdI_U->reset(ap_rst_n_inv);
    start_for_Mat2AXIwdI_U->if_read_ce(ap_var_for_const0);
    start_for_Mat2AXIwdI_U->if_write_ce(ap_var_for_const0);
    start_for_Mat2AXIwdI_U->if_din(start_for_Mat2AXIvideo_U0_din);
    start_for_Mat2AXIwdI_U->if_full_n(start_for_Mat2AXIvideo_U0_full_n);
    start_for_Mat2AXIwdI_U->if_write(CvtColor_1_U0_start_write);
    start_for_Mat2AXIwdI_U->if_dout(start_for_Mat2AXIvideo_U0_dout);
    start_for_Mat2AXIwdI_U->if_empty_n(start_for_Mat2AXIvideo_U0_empty_n);
    start_for_Mat2AXIwdI_U->if_read(Mat2AXIvideo_U0_ap_ready);

    SC_METHOD(thread_AXIvideo2Mat_U0_ap_continue);

    SC_METHOD(thread_AXIvideo2Mat_U0_ap_start);

    SC_METHOD(thread_AddWeighted_U0_ap_continue);

    SC_METHOD(thread_AddWeighted_U0_ap_start);
    sensitive << ( start_for_AddWeighted_U0_empty_n );

    SC_METHOD(thread_AddWeighted_U0_start_full_n);

    SC_METHOD(thread_AddWeighted_U0_start_write);

    SC_METHOD(thread_Block_proc232_U0_ap_continue);

    SC_METHOD(thread_Block_proc232_U0_ap_start);

    SC_METHOD(thread_CvtColor_1_U0_ap_continue);

    SC_METHOD(thread_CvtColor_1_U0_ap_start);
    sensitive << ( start_for_CvtColor_1_U0_empty_n );

    SC_METHOD(thread_CvtColor_U0_ap_continue);

    SC_METHOD(thread_CvtColor_U0_ap_start);
    sensitive << ( start_for_CvtColor_U0_empty_n );

    SC_METHOD(thread_Duplicate_U0_ap_continue);

    SC_METHOD(thread_Duplicate_U0_ap_start);
    sensitive << ( start_for_Duplicate_U0_empty_n );

    SC_METHOD(thread_Duplicate_U0_start_full_n);
    sensitive << ( start_for_Filter2D102_U0_full_n );
    sensitive << ( start_for_Filter2D_U0_full_n );

    SC_METHOD(thread_Filter2D102_U0_ap_continue);

    SC_METHOD(thread_Filter2D102_U0_ap_start);
    sensitive << ( start_for_Filter2D102_U0_empty_n );

    SC_METHOD(thread_Filter2D_U0_ap_continue);

    SC_METHOD(thread_Filter2D_U0_ap_start);
    sensitive << ( start_for_Filter2D_U0_empty_n );

    SC_METHOD(thread_Filter2D_U0_start_full_n);

    SC_METHOD(thread_Filter2D_U0_start_write);

    SC_METHOD(thread_Mat2AXIvideo_U0_ap_continue);

    SC_METHOD(thread_Mat2AXIvideo_U0_ap_start);
    sensitive << ( start_for_Mat2AXIvideo_U0_empty_n );

    SC_METHOD(thread_Mat2AXIvideo_U0_start_full_n);

    SC_METHOD(thread_Mat2AXIvideo_U0_start_write);

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_dst_TDATA);
    sensitive << ( Mat2AXIvideo_U0_dst_TDATA );

    SC_METHOD(thread_dst_TDEST);
    sensitive << ( Mat2AXIvideo_U0_dst_TDEST );

    SC_METHOD(thread_dst_TID);
    sensitive << ( Mat2AXIvideo_U0_dst_TID );

    SC_METHOD(thread_dst_TKEEP);
    sensitive << ( Mat2AXIvideo_U0_dst_TKEEP );

    SC_METHOD(thread_dst_TLAST);
    sensitive << ( Mat2AXIvideo_U0_dst_TLAST );

    SC_METHOD(thread_dst_TSTRB);
    sensitive << ( Mat2AXIvideo_U0_dst_TSTRB );

    SC_METHOD(thread_dst_TUSER);
    sensitive << ( Mat2AXIvideo_U0_dst_TUSER );

    SC_METHOD(thread_dst_TVALID);
    sensitive << ( Mat2AXIvideo_U0_dst_TVALID );

    SC_METHOD(thread_src_TREADY);
    sensitive << ( AXIvideo2Mat_U0_src_TREADY );

    SC_METHOD(thread_start_for_AddWeighted_U0_din);

    SC_METHOD(thread_start_for_CvtColor_1_U0_din);

    SC_METHOD(thread_start_for_CvtColor_U0_din);

    SC_METHOD(thread_start_for_Duplicate_U0_din);

    SC_METHOD(thread_start_for_Filter2D102_U0_din);

    SC_METHOD(thread_start_for_Filter2D_U0_din);

    SC_METHOD(thread_start_for_Mat2AXIvideo_U0_din);

    SC_METHOD(thread_start_for_thresholding_U0_din);

    SC_METHOD(thread_thresholding_U0_ap_continue);

    SC_METHOD(thread_thresholding_U0_ap_start);
    sensitive << ( start_for_thresholding_U0_empty_n );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "edge_detector_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, s_axi_AXILiteS_AWVALID, "(port)s_axi_AXILiteS_AWVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWREADY, "(port)s_axi_AXILiteS_AWREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_AWADDR, "(port)s_axi_AXILiteS_AWADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_WVALID, "(port)s_axi_AXILiteS_WVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_WREADY, "(port)s_axi_AXILiteS_WREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_WDATA, "(port)s_axi_AXILiteS_WDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_WSTRB, "(port)s_axi_AXILiteS_WSTRB");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARVALID, "(port)s_axi_AXILiteS_ARVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARREADY, "(port)s_axi_AXILiteS_ARREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_ARADDR, "(port)s_axi_AXILiteS_ARADDR");
    sc_trace(mVcdFile, s_axi_AXILiteS_RVALID, "(port)s_axi_AXILiteS_RVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_RREADY, "(port)s_axi_AXILiteS_RREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_RDATA, "(port)s_axi_AXILiteS_RDATA");
    sc_trace(mVcdFile, s_axi_AXILiteS_RRESP, "(port)s_axi_AXILiteS_RRESP");
    sc_trace(mVcdFile, s_axi_AXILiteS_BVALID, "(port)s_axi_AXILiteS_BVALID");
    sc_trace(mVcdFile, s_axi_AXILiteS_BREADY, "(port)s_axi_AXILiteS_BREADY");
    sc_trace(mVcdFile, s_axi_AXILiteS_BRESP, "(port)s_axi_AXILiteS_BRESP");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, src_TDATA, "(port)src_TDATA");
    sc_trace(mVcdFile, src_TKEEP, "(port)src_TKEEP");
    sc_trace(mVcdFile, src_TSTRB, "(port)src_TSTRB");
    sc_trace(mVcdFile, src_TUSER, "(port)src_TUSER");
    sc_trace(mVcdFile, src_TLAST, "(port)src_TLAST");
    sc_trace(mVcdFile, src_TID, "(port)src_TID");
    sc_trace(mVcdFile, src_TDEST, "(port)src_TDEST");
    sc_trace(mVcdFile, dst_TDATA, "(port)dst_TDATA");
    sc_trace(mVcdFile, dst_TKEEP, "(port)dst_TKEEP");
    sc_trace(mVcdFile, dst_TSTRB, "(port)dst_TSTRB");
    sc_trace(mVcdFile, dst_TUSER, "(port)dst_TUSER");
    sc_trace(mVcdFile, dst_TLAST, "(port)dst_TLAST");
    sc_trace(mVcdFile, dst_TID, "(port)dst_TID");
    sc_trace(mVcdFile, dst_TDEST, "(port)dst_TDEST");
    sc_trace(mVcdFile, src_TVALID, "(port)src_TVALID");
    sc_trace(mVcdFile, src_TREADY, "(port)src_TREADY");
    sc_trace(mVcdFile, dst_TVALID, "(port)dst_TVALID");
    sc_trace(mVcdFile, dst_TREADY, "(port)dst_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, threshold, "threshold");
    sc_trace(mVcdFile, Block_proc232_U0_ap_start, "Block_proc232_U0_ap_start");
    sc_trace(mVcdFile, Block_proc232_U0_ap_done, "Block_proc232_U0_ap_done");
    sc_trace(mVcdFile, Block_proc232_U0_ap_continue, "Block_proc232_U0_ap_continue");
    sc_trace(mVcdFile, Block_proc232_U0_ap_idle, "Block_proc232_U0_ap_idle");
    sc_trace(mVcdFile, Block_proc232_U0_ap_ready, "Block_proc232_U0_ap_ready");
    sc_trace(mVcdFile, Block_proc232_U0_start_out, "Block_proc232_U0_start_out");
    sc_trace(mVcdFile, Block_proc232_U0_start_write, "Block_proc232_U0_start_write");
    sc_trace(mVcdFile, Block_proc232_U0_srcImg_rows_V_out_din, "Block_proc232_U0_srcImg_rows_V_out_din");
    sc_trace(mVcdFile, Block_proc232_U0_srcImg_rows_V_out_write, "Block_proc232_U0_srcImg_rows_V_out_write");
    sc_trace(mVcdFile, Block_proc232_U0_srcImg_cols_V_out_din, "Block_proc232_U0_srcImg_cols_V_out_din");
    sc_trace(mVcdFile, Block_proc232_U0_srcImg_cols_V_out_write, "Block_proc232_U0_srcImg_cols_V_out_write");
    sc_trace(mVcdFile, Block_proc232_U0_threshold_out_din, "Block_proc232_U0_threshold_out_din");
    sc_trace(mVcdFile, Block_proc232_U0_threshold_out_write, "Block_proc232_U0_threshold_out_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_start, "AXIvideo2Mat_U0_ap_start");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_done, "AXIvideo2Mat_U0_ap_done");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_continue, "AXIvideo2Mat_U0_ap_continue");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_idle, "AXIvideo2Mat_U0_ap_idle");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_ready, "AXIvideo2Mat_U0_ap_ready");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_start_out, "AXIvideo2Mat_U0_start_out");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_start_write, "AXIvideo2Mat_U0_start_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_src_TREADY, "AXIvideo2Mat_U0_src_TREADY");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_read, "AXIvideo2Mat_U0_img_rows_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_read, "AXIvideo2Mat_U0_img_cols_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_0_V_din, "AXIvideo2Mat_U0_img_data_stream_0_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_0_V_write, "AXIvideo2Mat_U0_img_data_stream_0_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_1_V_din, "AXIvideo2Mat_U0_img_data_stream_1_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_1_V_write, "AXIvideo2Mat_U0_img_data_stream_1_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_2_V_din, "AXIvideo2Mat_U0_img_data_stream_2_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_2_V_write, "AXIvideo2Mat_U0_img_data_stream_2_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_out_din, "AXIvideo2Mat_U0_img_rows_V_out_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_out_write, "AXIvideo2Mat_U0_img_rows_V_out_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_out_din, "AXIvideo2Mat_U0_img_cols_V_out_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_out_write, "AXIvideo2Mat_U0_img_cols_V_out_write");
    sc_trace(mVcdFile, CvtColor_U0_ap_start, "CvtColor_U0_ap_start");
    sc_trace(mVcdFile, CvtColor_U0_ap_done, "CvtColor_U0_ap_done");
    sc_trace(mVcdFile, CvtColor_U0_ap_continue, "CvtColor_U0_ap_continue");
    sc_trace(mVcdFile, CvtColor_U0_ap_idle, "CvtColor_U0_ap_idle");
    sc_trace(mVcdFile, CvtColor_U0_ap_ready, "CvtColor_U0_ap_ready");
    sc_trace(mVcdFile, CvtColor_U0_start_out, "CvtColor_U0_start_out");
    sc_trace(mVcdFile, CvtColor_U0_start_write, "CvtColor_U0_start_write");
    sc_trace(mVcdFile, CvtColor_U0_p_src_rows_V_read, "CvtColor_U0_p_src_rows_V_read");
    sc_trace(mVcdFile, CvtColor_U0_p_src_cols_V_read, "CvtColor_U0_p_src_cols_V_read");
    sc_trace(mVcdFile, CvtColor_U0_p_src_data_stream_0_V_read, "CvtColor_U0_p_src_data_stream_0_V_read");
    sc_trace(mVcdFile, CvtColor_U0_p_src_data_stream_1_V_read, "CvtColor_U0_p_src_data_stream_1_V_read");
    sc_trace(mVcdFile, CvtColor_U0_p_src_data_stream_2_V_read, "CvtColor_U0_p_src_data_stream_2_V_read");
    sc_trace(mVcdFile, CvtColor_U0_p_dst_data_stream_V_din, "CvtColor_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, CvtColor_U0_p_dst_data_stream_V_write, "CvtColor_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, Duplicate_U0_ap_start, "Duplicate_U0_ap_start");
    sc_trace(mVcdFile, Duplicate_U0_start_full_n, "Duplicate_U0_start_full_n");
    sc_trace(mVcdFile, Duplicate_U0_ap_done, "Duplicate_U0_ap_done");
    sc_trace(mVcdFile, Duplicate_U0_ap_continue, "Duplicate_U0_ap_continue");
    sc_trace(mVcdFile, Duplicate_U0_ap_idle, "Duplicate_U0_ap_idle");
    sc_trace(mVcdFile, Duplicate_U0_ap_ready, "Duplicate_U0_ap_ready");
    sc_trace(mVcdFile, Duplicate_U0_start_out, "Duplicate_U0_start_out");
    sc_trace(mVcdFile, Duplicate_U0_start_write, "Duplicate_U0_start_write");
    sc_trace(mVcdFile, Duplicate_U0_src_data_stream_V_read, "Duplicate_U0_src_data_stream_V_read");
    sc_trace(mVcdFile, Duplicate_U0_dst1_data_stream_V_din, "Duplicate_U0_dst1_data_stream_V_din");
    sc_trace(mVcdFile, Duplicate_U0_dst1_data_stream_V_write, "Duplicate_U0_dst1_data_stream_V_write");
    sc_trace(mVcdFile, Duplicate_U0_dst2_data_stream_V_din, "Duplicate_U0_dst2_data_stream_V_din");
    sc_trace(mVcdFile, Duplicate_U0_dst2_data_stream_V_write, "Duplicate_U0_dst2_data_stream_V_write");
    sc_trace(mVcdFile, Filter2D102_U0_ap_start, "Filter2D102_U0_ap_start");
    sc_trace(mVcdFile, Filter2D102_U0_ap_done, "Filter2D102_U0_ap_done");
    sc_trace(mVcdFile, Filter2D102_U0_ap_continue, "Filter2D102_U0_ap_continue");
    sc_trace(mVcdFile, Filter2D102_U0_ap_idle, "Filter2D102_U0_ap_idle");
    sc_trace(mVcdFile, Filter2D102_U0_ap_ready, "Filter2D102_U0_ap_ready");
    sc_trace(mVcdFile, Filter2D102_U0_start_out, "Filter2D102_U0_start_out");
    sc_trace(mVcdFile, Filter2D102_U0_start_write, "Filter2D102_U0_start_write");
    sc_trace(mVcdFile, Filter2D102_U0_p_src_data_stream_V_read, "Filter2D102_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, Filter2D102_U0_p_dst_data_stream_V_din, "Filter2D102_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, Filter2D102_U0_p_dst_data_stream_V_write, "Filter2D102_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, Filter2D_U0_ap_start, "Filter2D_U0_ap_start");
    sc_trace(mVcdFile, Filter2D_U0_ap_done, "Filter2D_U0_ap_done");
    sc_trace(mVcdFile, Filter2D_U0_ap_continue, "Filter2D_U0_ap_continue");
    sc_trace(mVcdFile, Filter2D_U0_ap_idle, "Filter2D_U0_ap_idle");
    sc_trace(mVcdFile, Filter2D_U0_ap_ready, "Filter2D_U0_ap_ready");
    sc_trace(mVcdFile, Filter2D_U0_p_src_data_stream_V_read, "Filter2D_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, Filter2D_U0_p_dst_data_stream_V_din, "Filter2D_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, Filter2D_U0_p_dst_data_stream_V_write, "Filter2D_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, AddWeighted_U0_ap_start, "AddWeighted_U0_ap_start");
    sc_trace(mVcdFile, AddWeighted_U0_ap_done, "AddWeighted_U0_ap_done");
    sc_trace(mVcdFile, AddWeighted_U0_ap_continue, "AddWeighted_U0_ap_continue");
    sc_trace(mVcdFile, AddWeighted_U0_ap_idle, "AddWeighted_U0_ap_idle");
    sc_trace(mVcdFile, AddWeighted_U0_ap_ready, "AddWeighted_U0_ap_ready");
    sc_trace(mVcdFile, AddWeighted_U0_src1_data_stream_V_read, "AddWeighted_U0_src1_data_stream_V_read");
    sc_trace(mVcdFile, AddWeighted_U0_src2_data_stream_V_read, "AddWeighted_U0_src2_data_stream_V_read");
    sc_trace(mVcdFile, AddWeighted_U0_dst_data_stream_V_din, "AddWeighted_U0_dst_data_stream_V_din");
    sc_trace(mVcdFile, AddWeighted_U0_dst_data_stream_V_write, "AddWeighted_U0_dst_data_stream_V_write");
    sc_trace(mVcdFile, thresholding_U0_ap_start, "thresholding_U0_ap_start");
    sc_trace(mVcdFile, thresholding_U0_ap_done, "thresholding_U0_ap_done");
    sc_trace(mVcdFile, thresholding_U0_ap_continue, "thresholding_U0_ap_continue");
    sc_trace(mVcdFile, thresholding_U0_ap_idle, "thresholding_U0_ap_idle");
    sc_trace(mVcdFile, thresholding_U0_ap_ready, "thresholding_U0_ap_ready");
    sc_trace(mVcdFile, thresholding_U0_start_out, "thresholding_U0_start_out");
    sc_trace(mVcdFile, thresholding_U0_start_write, "thresholding_U0_start_write");
    sc_trace(mVcdFile, thresholding_U0_dst_data_stream_V_din, "thresholding_U0_dst_data_stream_V_din");
    sc_trace(mVcdFile, thresholding_U0_dst_data_stream_V_write, "thresholding_U0_dst_data_stream_V_write");
    sc_trace(mVcdFile, thresholding_U0_src_data_stream_V_read, "thresholding_U0_src_data_stream_V_read");
    sc_trace(mVcdFile, thresholding_U0_threshold_read, "thresholding_U0_threshold_read");
    sc_trace(mVcdFile, CvtColor_1_U0_ap_start, "CvtColor_1_U0_ap_start");
    sc_trace(mVcdFile, CvtColor_1_U0_ap_done, "CvtColor_1_U0_ap_done");
    sc_trace(mVcdFile, CvtColor_1_U0_ap_continue, "CvtColor_1_U0_ap_continue");
    sc_trace(mVcdFile, CvtColor_1_U0_ap_idle, "CvtColor_1_U0_ap_idle");
    sc_trace(mVcdFile, CvtColor_1_U0_ap_ready, "CvtColor_1_U0_ap_ready");
    sc_trace(mVcdFile, CvtColor_1_U0_start_out, "CvtColor_1_U0_start_out");
    sc_trace(mVcdFile, CvtColor_1_U0_start_write, "CvtColor_1_U0_start_write");
    sc_trace(mVcdFile, CvtColor_1_U0_p_src_data_stream_V_read, "CvtColor_1_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, CvtColor_1_U0_p_dst_data_stream_0_V_din, "CvtColor_1_U0_p_dst_data_stream_0_V_din");
    sc_trace(mVcdFile, CvtColor_1_U0_p_dst_data_stream_0_V_write, "CvtColor_1_U0_p_dst_data_stream_0_V_write");
    sc_trace(mVcdFile, CvtColor_1_U0_p_dst_data_stream_1_V_din, "CvtColor_1_U0_p_dst_data_stream_1_V_din");
    sc_trace(mVcdFile, CvtColor_1_U0_p_dst_data_stream_1_V_write, "CvtColor_1_U0_p_dst_data_stream_1_V_write");
    sc_trace(mVcdFile, CvtColor_1_U0_p_dst_data_stream_2_V_din, "CvtColor_1_U0_p_dst_data_stream_2_V_din");
    sc_trace(mVcdFile, CvtColor_1_U0_p_dst_data_stream_2_V_write, "CvtColor_1_U0_p_dst_data_stream_2_V_write");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_start, "Mat2AXIvideo_U0_ap_start");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_done, "Mat2AXIvideo_U0_ap_done");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_continue, "Mat2AXIvideo_U0_ap_continue");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_idle, "Mat2AXIvideo_U0_ap_idle");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_ready, "Mat2AXIvideo_U0_ap_ready");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_0_V_read, "Mat2AXIvideo_U0_img_data_stream_0_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_1_V_read, "Mat2AXIvideo_U0_img_data_stream_1_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_2_V_read, "Mat2AXIvideo_U0_img_data_stream_2_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_dst_TDATA, "Mat2AXIvideo_U0_dst_TDATA");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_dst_TVALID, "Mat2AXIvideo_U0_dst_TVALID");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_dst_TKEEP, "Mat2AXIvideo_U0_dst_TKEEP");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_dst_TSTRB, "Mat2AXIvideo_U0_dst_TSTRB");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_dst_TUSER, "Mat2AXIvideo_U0_dst_TUSER");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_dst_TLAST, "Mat2AXIvideo_U0_dst_TLAST");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_dst_TID, "Mat2AXIvideo_U0_dst_TID");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_dst_TDEST, "Mat2AXIvideo_U0_dst_TDEST");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, srcImg_rows_V_c_full_n, "srcImg_rows_V_c_full_n");
    sc_trace(mVcdFile, srcImg_rows_V_c_dout, "srcImg_rows_V_c_dout");
    sc_trace(mVcdFile, srcImg_rows_V_c_empty_n, "srcImg_rows_V_c_empty_n");
    sc_trace(mVcdFile, srcImg_cols_V_c_full_n, "srcImg_cols_V_c_full_n");
    sc_trace(mVcdFile, srcImg_cols_V_c_dout, "srcImg_cols_V_c_dout");
    sc_trace(mVcdFile, srcImg_cols_V_c_empty_n, "srcImg_cols_V_c_empty_n");
    sc_trace(mVcdFile, threshold_c_full_n, "threshold_c_full_n");
    sc_trace(mVcdFile, threshold_c_dout, "threshold_c_dout");
    sc_trace(mVcdFile, threshold_c_empty_n, "threshold_c_empty_n");
    sc_trace(mVcdFile, srcImg_data_stream_0_full_n, "srcImg_data_stream_0_full_n");
    sc_trace(mVcdFile, srcImg_data_stream_0_dout, "srcImg_data_stream_0_dout");
    sc_trace(mVcdFile, srcImg_data_stream_0_empty_n, "srcImg_data_stream_0_empty_n");
    sc_trace(mVcdFile, srcImg_data_stream_1_full_n, "srcImg_data_stream_1_full_n");
    sc_trace(mVcdFile, srcImg_data_stream_1_dout, "srcImg_data_stream_1_dout");
    sc_trace(mVcdFile, srcImg_data_stream_1_empty_n, "srcImg_data_stream_1_empty_n");
    sc_trace(mVcdFile, srcImg_data_stream_2_full_n, "srcImg_data_stream_2_full_n");
    sc_trace(mVcdFile, srcImg_data_stream_2_dout, "srcImg_data_stream_2_dout");
    sc_trace(mVcdFile, srcImg_data_stream_2_empty_n, "srcImg_data_stream_2_empty_n");
    sc_trace(mVcdFile, srcImg_rows_V_c20_full_n, "srcImg_rows_V_c20_full_n");
    sc_trace(mVcdFile, srcImg_rows_V_c20_dout, "srcImg_rows_V_c20_dout");
    sc_trace(mVcdFile, srcImg_rows_V_c20_empty_n, "srcImg_rows_V_c20_empty_n");
    sc_trace(mVcdFile, srcImg_cols_V_c21_full_n, "srcImg_cols_V_c21_full_n");
    sc_trace(mVcdFile, srcImg_cols_V_c21_dout, "srcImg_cols_V_c21_dout");
    sc_trace(mVcdFile, srcImg_cols_V_c21_empty_n, "srcImg_cols_V_c21_empty_n");
    sc_trace(mVcdFile, grayImg_data_stream_s_full_n, "grayImg_data_stream_s_full_n");
    sc_trace(mVcdFile, grayImg_data_stream_s_dout, "grayImg_data_stream_s_dout");
    sc_trace(mVcdFile, grayImg_data_stream_s_empty_n, "grayImg_data_stream_s_empty_n");
    sc_trace(mVcdFile, split0_data_stream_0_full_n, "split0_data_stream_0_full_n");
    sc_trace(mVcdFile, split0_data_stream_0_dout, "split0_data_stream_0_dout");
    sc_trace(mVcdFile, split0_data_stream_0_empty_n, "split0_data_stream_0_empty_n");
    sc_trace(mVcdFile, split1_data_stream_0_full_n, "split1_data_stream_0_full_n");
    sc_trace(mVcdFile, split1_data_stream_0_dout, "split1_data_stream_0_dout");
    sc_trace(mVcdFile, split1_data_stream_0_empty_n, "split1_data_stream_0_empty_n");
    sc_trace(mVcdFile, sobelImg_x_data_stre_full_n, "sobelImg_x_data_stre_full_n");
    sc_trace(mVcdFile, sobelImg_x_data_stre_dout, "sobelImg_x_data_stre_dout");
    sc_trace(mVcdFile, sobelImg_x_data_stre_empty_n, "sobelImg_x_data_stre_empty_n");
    sc_trace(mVcdFile, sobelImg_y_data_stre_full_n, "sobelImg_y_data_stre_full_n");
    sc_trace(mVcdFile, sobelImg_y_data_stre_dout, "sobelImg_y_data_stre_dout");
    sc_trace(mVcdFile, sobelImg_y_data_stre_empty_n, "sobelImg_y_data_stre_empty_n");
    sc_trace(mVcdFile, sobelImg_data_stream_full_n, "sobelImg_data_stream_full_n");
    sc_trace(mVcdFile, sobelImg_data_stream_dout, "sobelImg_data_stream_dout");
    sc_trace(mVcdFile, sobelImg_data_stream_empty_n, "sobelImg_data_stream_empty_n");
    sc_trace(mVcdFile, thresholdImg_data_st_full_n, "thresholdImg_data_st_full_n");
    sc_trace(mVcdFile, thresholdImg_data_st_dout, "thresholdImg_data_st_dout");
    sc_trace(mVcdFile, thresholdImg_data_st_empty_n, "thresholdImg_data_st_empty_n");
    sc_trace(mVcdFile, rgbSobel_data_stream_full_n, "rgbSobel_data_stream_full_n");
    sc_trace(mVcdFile, rgbSobel_data_stream_dout, "rgbSobel_data_stream_dout");
    sc_trace(mVcdFile, rgbSobel_data_stream_empty_n, "rgbSobel_data_stream_empty_n");
    sc_trace(mVcdFile, rgbSobel_data_stream_1_full_n, "rgbSobel_data_stream_1_full_n");
    sc_trace(mVcdFile, rgbSobel_data_stream_1_dout, "rgbSobel_data_stream_1_dout");
    sc_trace(mVcdFile, rgbSobel_data_stream_1_empty_n, "rgbSobel_data_stream_1_empty_n");
    sc_trace(mVcdFile, rgbSobel_data_stream_2_full_n, "rgbSobel_data_stream_2_full_n");
    sc_trace(mVcdFile, rgbSobel_data_stream_2_dout, "rgbSobel_data_stream_2_dout");
    sc_trace(mVcdFile, rgbSobel_data_stream_2_empty_n, "rgbSobel_data_stream_2_empty_n");
    sc_trace(mVcdFile, start_for_thresholding_U0_din, "start_for_thresholding_U0_din");
    sc_trace(mVcdFile, start_for_thresholding_U0_full_n, "start_for_thresholding_U0_full_n");
    sc_trace(mVcdFile, start_for_thresholding_U0_dout, "start_for_thresholding_U0_dout");
    sc_trace(mVcdFile, start_for_thresholding_U0_empty_n, "start_for_thresholding_U0_empty_n");
    sc_trace(mVcdFile, start_for_CvtColor_U0_din, "start_for_CvtColor_U0_din");
    sc_trace(mVcdFile, start_for_CvtColor_U0_full_n, "start_for_CvtColor_U0_full_n");
    sc_trace(mVcdFile, start_for_CvtColor_U0_dout, "start_for_CvtColor_U0_dout");
    sc_trace(mVcdFile, start_for_CvtColor_U0_empty_n, "start_for_CvtColor_U0_empty_n");
    sc_trace(mVcdFile, start_for_Duplicate_U0_din, "start_for_Duplicate_U0_din");
    sc_trace(mVcdFile, start_for_Duplicate_U0_full_n, "start_for_Duplicate_U0_full_n");
    sc_trace(mVcdFile, start_for_Duplicate_U0_dout, "start_for_Duplicate_U0_dout");
    sc_trace(mVcdFile, start_for_Duplicate_U0_empty_n, "start_for_Duplicate_U0_empty_n");
    sc_trace(mVcdFile, start_for_Filter2D102_U0_din, "start_for_Filter2D102_U0_din");
    sc_trace(mVcdFile, start_for_Filter2D102_U0_full_n, "start_for_Filter2D102_U0_full_n");
    sc_trace(mVcdFile, start_for_Filter2D102_U0_dout, "start_for_Filter2D102_U0_dout");
    sc_trace(mVcdFile, start_for_Filter2D102_U0_empty_n, "start_for_Filter2D102_U0_empty_n");
    sc_trace(mVcdFile, start_for_Filter2D_U0_din, "start_for_Filter2D_U0_din");
    sc_trace(mVcdFile, start_for_Filter2D_U0_full_n, "start_for_Filter2D_U0_full_n");
    sc_trace(mVcdFile, start_for_Filter2D_U0_dout, "start_for_Filter2D_U0_dout");
    sc_trace(mVcdFile, start_for_Filter2D_U0_empty_n, "start_for_Filter2D_U0_empty_n");
    sc_trace(mVcdFile, start_for_AddWeighted_U0_din, "start_for_AddWeighted_U0_din");
    sc_trace(mVcdFile, start_for_AddWeighted_U0_full_n, "start_for_AddWeighted_U0_full_n");
    sc_trace(mVcdFile, start_for_AddWeighted_U0_dout, "start_for_AddWeighted_U0_dout");
    sc_trace(mVcdFile, start_for_AddWeighted_U0_empty_n, "start_for_AddWeighted_U0_empty_n");
    sc_trace(mVcdFile, Filter2D_U0_start_full_n, "Filter2D_U0_start_full_n");
    sc_trace(mVcdFile, Filter2D_U0_start_write, "Filter2D_U0_start_write");
    sc_trace(mVcdFile, AddWeighted_U0_start_full_n, "AddWeighted_U0_start_full_n");
    sc_trace(mVcdFile, AddWeighted_U0_start_write, "AddWeighted_U0_start_write");
    sc_trace(mVcdFile, start_for_CvtColor_1_U0_din, "start_for_CvtColor_1_U0_din");
    sc_trace(mVcdFile, start_for_CvtColor_1_U0_full_n, "start_for_CvtColor_1_U0_full_n");
    sc_trace(mVcdFile, start_for_CvtColor_1_U0_dout, "start_for_CvtColor_1_U0_dout");
    sc_trace(mVcdFile, start_for_CvtColor_1_U0_empty_n, "start_for_CvtColor_1_U0_empty_n");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_din, "start_for_Mat2AXIvideo_U0_din");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_full_n, "start_for_Mat2AXIvideo_U0_full_n");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_dout, "start_for_Mat2AXIvideo_U0_dout");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_empty_n, "start_for_Mat2AXIvideo_U0_empty_n");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_start_full_n, "Mat2AXIvideo_U0_start_full_n");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_start_write, "Mat2AXIvideo_U0_start_write");
#endif

    }
    mHdltvinHandle.open("edge_detector.hdltvin.dat");
    mHdltvoutHandle.open("edge_detector.hdltvout.dat");
}

edge_detector::~edge_detector() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete edge_detector_AXILiteS_s_axi_U;
    delete Block_proc232_U0;
    delete AXIvideo2Mat_U0;
    delete CvtColor_U0;
    delete Duplicate_U0;
    delete Filter2D102_U0;
    delete Filter2D_U0;
    delete AddWeighted_U0;
    delete thresholding_U0;
    delete CvtColor_1_U0;
    delete Mat2AXIvideo_U0;
    delete srcImg_rows_V_c_U;
    delete srcImg_cols_V_c_U;
    delete threshold_c_U;
    delete srcImg_data_stream_0_U;
    delete srcImg_data_stream_1_U;
    delete srcImg_data_stream_2_U;
    delete srcImg_rows_V_c20_U;
    delete srcImg_cols_V_c21_U;
    delete grayImg_data_stream_s_U;
    delete split0_data_stream_0_U;
    delete split1_data_stream_0_U;
    delete sobelImg_x_data_stre_U;
    delete sobelImg_y_data_stre_U;
    delete sobelImg_data_stream_U;
    delete thresholdImg_data_st_U;
    delete rgbSobel_data_stream_U;
    delete rgbSobel_data_stream_1_U;
    delete rgbSobel_data_stream_2_U;
    delete start_for_threshopcA_U;
    delete start_for_CvtColoqcK_U;
    delete start_for_DuplicarcU_U;
    delete start_for_Filter2sc4_U;
    delete start_for_Filter2tde_U;
    delete start_for_AddWeigudo_U;
    delete start_for_CvtColovdy_U;
    delete start_for_Mat2AXIwdI_U;
}

void edge_detector::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void edge_detector::thread_AXIvideo2Mat_U0_ap_continue() {
    AXIvideo2Mat_U0_ap_continue = ap_const_logic_1;
}

void edge_detector::thread_AXIvideo2Mat_U0_ap_start() {
    AXIvideo2Mat_U0_ap_start = ap_const_logic_1;
}

void edge_detector::thread_AddWeighted_U0_ap_continue() {
    AddWeighted_U0_ap_continue = ap_const_logic_1;
}

void edge_detector::thread_AddWeighted_U0_ap_start() {
    AddWeighted_U0_ap_start = start_for_AddWeighted_U0_empty_n.read();
}

void edge_detector::thread_AddWeighted_U0_start_full_n() {
    AddWeighted_U0_start_full_n = ap_const_logic_1;
}

void edge_detector::thread_AddWeighted_U0_start_write() {
    AddWeighted_U0_start_write = ap_const_logic_0;
}

void edge_detector::thread_Block_proc232_U0_ap_continue() {
    Block_proc232_U0_ap_continue = ap_const_logic_1;
}

void edge_detector::thread_Block_proc232_U0_ap_start() {
    Block_proc232_U0_ap_start = ap_const_logic_1;
}

void edge_detector::thread_CvtColor_1_U0_ap_continue() {
    CvtColor_1_U0_ap_continue = ap_const_logic_1;
}

void edge_detector::thread_CvtColor_1_U0_ap_start() {
    CvtColor_1_U0_ap_start = start_for_CvtColor_1_U0_empty_n.read();
}

void edge_detector::thread_CvtColor_U0_ap_continue() {
    CvtColor_U0_ap_continue = ap_const_logic_1;
}

void edge_detector::thread_CvtColor_U0_ap_start() {
    CvtColor_U0_ap_start = start_for_CvtColor_U0_empty_n.read();
}

void edge_detector::thread_Duplicate_U0_ap_continue() {
    Duplicate_U0_ap_continue = ap_const_logic_1;
}

void edge_detector::thread_Duplicate_U0_ap_start() {
    Duplicate_U0_ap_start = start_for_Duplicate_U0_empty_n.read();
}

void edge_detector::thread_Duplicate_U0_start_full_n() {
    Duplicate_U0_start_full_n = (start_for_Filter2D102_U0_full_n.read() & start_for_Filter2D_U0_full_n.read());
}

void edge_detector::thread_Filter2D102_U0_ap_continue() {
    Filter2D102_U0_ap_continue = ap_const_logic_1;
}

void edge_detector::thread_Filter2D102_U0_ap_start() {
    Filter2D102_U0_ap_start = start_for_Filter2D102_U0_empty_n.read();
}

void edge_detector::thread_Filter2D_U0_ap_continue() {
    Filter2D_U0_ap_continue = ap_const_logic_1;
}

void edge_detector::thread_Filter2D_U0_ap_start() {
    Filter2D_U0_ap_start = start_for_Filter2D_U0_empty_n.read();
}

void edge_detector::thread_Filter2D_U0_start_full_n() {
    Filter2D_U0_start_full_n = ap_const_logic_1;
}

void edge_detector::thread_Filter2D_U0_start_write() {
    Filter2D_U0_start_write = ap_const_logic_0;
}

void edge_detector::thread_Mat2AXIvideo_U0_ap_continue() {
    Mat2AXIvideo_U0_ap_continue = ap_const_logic_1;
}

void edge_detector::thread_Mat2AXIvideo_U0_ap_start() {
    Mat2AXIvideo_U0_ap_start = start_for_Mat2AXIvideo_U0_empty_n.read();
}

void edge_detector::thread_Mat2AXIvideo_U0_start_full_n() {
    Mat2AXIvideo_U0_start_full_n = ap_const_logic_1;
}

void edge_detector::thread_Mat2AXIvideo_U0_start_write() {
    Mat2AXIvideo_U0_start_write = ap_const_logic_0;
}

void edge_detector::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void edge_detector::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_0;
}

void edge_detector::thread_dst_TDATA() {
    dst_TDATA = Mat2AXIvideo_U0_dst_TDATA.read();
}

void edge_detector::thread_dst_TDEST() {
    dst_TDEST = Mat2AXIvideo_U0_dst_TDEST.read();
}

void edge_detector::thread_dst_TID() {
    dst_TID = Mat2AXIvideo_U0_dst_TID.read();
}

void edge_detector::thread_dst_TKEEP() {
    dst_TKEEP = Mat2AXIvideo_U0_dst_TKEEP.read();
}

void edge_detector::thread_dst_TLAST() {
    dst_TLAST = Mat2AXIvideo_U0_dst_TLAST.read();
}

void edge_detector::thread_dst_TSTRB() {
    dst_TSTRB = Mat2AXIvideo_U0_dst_TSTRB.read();
}

void edge_detector::thread_dst_TUSER() {
    dst_TUSER = Mat2AXIvideo_U0_dst_TUSER.read();
}

void edge_detector::thread_dst_TVALID() {
    dst_TVALID = Mat2AXIvideo_U0_dst_TVALID.read();
}

void edge_detector::thread_src_TREADY() {
    src_TREADY = AXIvideo2Mat_U0_src_TREADY.read();
}

void edge_detector::thread_start_for_AddWeighted_U0_din() {
    start_for_AddWeighted_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void edge_detector::thread_start_for_CvtColor_1_U0_din() {
    start_for_CvtColor_1_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void edge_detector::thread_start_for_CvtColor_U0_din() {
    start_for_CvtColor_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void edge_detector::thread_start_for_Duplicate_U0_din() {
    start_for_Duplicate_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void edge_detector::thread_start_for_Filter2D102_U0_din() {
    start_for_Filter2D102_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void edge_detector::thread_start_for_Filter2D_U0_din() {
    start_for_Filter2D_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void edge_detector::thread_start_for_Mat2AXIvideo_U0_din() {
    start_for_Mat2AXIvideo_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void edge_detector::thread_start_for_thresholding_U0_din() {
    start_for_thresholding_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void edge_detector::thread_thresholding_U0_ap_continue() {
    thresholding_U0_ap_continue = ap_const_logic_1;
}

void edge_detector::thread_thresholding_U0_ap_start() {
    thresholding_U0_ap_start = start_for_thresholding_U0_empty_n.read();
}

void edge_detector::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"s_axi_AXILiteS_AWVALID\" :  \"" << s_axi_AXILiteS_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_AXILiteS_AWREADY\" :  \"" << s_axi_AXILiteS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_AWADDR\" :  \"" << s_axi_AXILiteS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WVALID\" :  \"" << s_axi_AXILiteS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_WREADY\" :  \"" << s_axi_AXILiteS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WDATA\" :  \"" << s_axi_AXILiteS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_WSTRB\" :  \"" << s_axi_AXILiteS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARVALID\" :  \"" << s_axi_AXILiteS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_ARREADY\" :  \"" << s_axi_AXILiteS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_ARADDR\" :  \"" << s_axi_AXILiteS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RVALID\" :  \"" << s_axi_AXILiteS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_RREADY\" :  \"" << s_axi_AXILiteS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RDATA\" :  \"" << s_axi_AXILiteS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_RRESP\" :  \"" << s_axi_AXILiteS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BVALID\" :  \"" << s_axi_AXILiteS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_AXILiteS_BREADY\" :  \"" << s_axi_AXILiteS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_AXILiteS_BRESP\" :  \"" << s_axi_AXILiteS_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"src_TDATA\" :  \"" << src_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"src_TKEEP\" :  \"" << src_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"src_TSTRB\" :  \"" << src_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"src_TUSER\" :  \"" << src_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"src_TLAST\" :  \"" << src_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"src_TID\" :  \"" << src_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"src_TDEST\" :  \"" << src_TDEST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dst_TDATA\" :  \"" << dst_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dst_TKEEP\" :  \"" << dst_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dst_TSTRB\" :  \"" << dst_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dst_TUSER\" :  \"" << dst_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dst_TLAST\" :  \"" << dst_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dst_TID\" :  \"" << dst_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dst_TDEST\" :  \"" << dst_TDEST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"src_TVALID\" :  \"" << src_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"src_TREADY\" :  \"" << src_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dst_TVALID\" :  \"" << dst_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"dst_TREADY\" :  \"" << dst_TREADY.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

