// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module AddWeighted (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        src1_data_stream_V_dout,
        src1_data_stream_V_empty_n,
        src1_data_stream_V_read,
        src2_data_stream_V_dout,
        src2_data_stream_V_empty_n,
        src2_data_stream_V_read,
        dst_data_stream_V_din,
        dst_data_stream_V_full_n,
        dst_data_stream_V_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state34 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] src1_data_stream_V_dout;
input   src1_data_stream_V_empty_n;
output   src1_data_stream_V_read;
input  [7:0] src2_data_stream_V_dout;
input   src2_data_stream_V_empty_n;
output   src2_data_stream_V_read;
output  [7:0] dst_data_stream_V_din;
input   dst_data_stream_V_full_n;
output   dst_data_stream_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg src1_data_stream_V_read;
reg src2_data_stream_V_read;
reg dst_data_stream_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    src1_data_stream_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond_i_reg_976;
reg    src2_data_stream_V_blk_n;
reg    dst_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter30;
reg   [0:0] exitcond_i_reg_976_pp0_iter29_reg;
reg   [10:0] t_V_5_reg_194;
wire   [0:0] exitcond1_i_fu_233_p2;
wire    ap_CS_fsm_state2;
wire   [10:0] i_V_fu_239_p2;
reg   [10:0] i_V_reg_971;
wire   [0:0] exitcond_i_fu_245_p2;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
wire    ap_block_state7_pp0_stage0_iter4;
wire    ap_block_state8_pp0_stage0_iter5;
wire    ap_block_state9_pp0_stage0_iter6;
wire    ap_block_state10_pp0_stage0_iter7;
wire    ap_block_state11_pp0_stage0_iter8;
wire    ap_block_state12_pp0_stage0_iter9;
wire    ap_block_state13_pp0_stage0_iter10;
wire    ap_block_state14_pp0_stage0_iter11;
wire    ap_block_state15_pp0_stage0_iter12;
wire    ap_block_state16_pp0_stage0_iter13;
wire    ap_block_state17_pp0_stage0_iter14;
wire    ap_block_state18_pp0_stage0_iter15;
wire    ap_block_state19_pp0_stage0_iter16;
wire    ap_block_state20_pp0_stage0_iter17;
wire    ap_block_state21_pp0_stage0_iter18;
wire    ap_block_state22_pp0_stage0_iter19;
wire    ap_block_state23_pp0_stage0_iter20;
wire    ap_block_state24_pp0_stage0_iter21;
wire    ap_block_state25_pp0_stage0_iter22;
wire    ap_block_state26_pp0_stage0_iter23;
wire    ap_block_state27_pp0_stage0_iter24;
wire    ap_block_state28_pp0_stage0_iter25;
wire    ap_block_state29_pp0_stage0_iter26;
wire    ap_block_state30_pp0_stage0_iter27;
wire    ap_block_state31_pp0_stage0_iter28;
wire    ap_block_state32_pp0_stage0_iter29;
reg    ap_block_state33_pp0_stage0_iter30;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond_i_reg_976_pp0_iter1_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter2_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter3_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter4_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter5_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter6_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter7_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter8_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter9_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter10_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter11_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter12_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter13_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter14_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter15_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter16_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter17_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter18_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter19_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter20_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter21_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter22_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter23_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter24_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter25_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter26_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter27_reg;
reg   [0:0] exitcond_i_reg_976_pp0_iter28_reg;
wire   [10:0] j_V_fu_251_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [7:0] tmp_reg_985;
reg   [7:0] tmp_59_reg_990;
wire   [31:0] grp_fu_224_p1;
reg   [31:0] tmp_i_99_reg_1005;
wire   [31:0] grp_fu_227_p1;
reg   [31:0] tmp_36_i_reg_1010;
wire   [31:0] grp_fu_214_p2;
reg   [31:0] t1_reg_1015;
wire   [31:0] grp_fu_219_p2;
reg   [31:0] t2_reg_1020;
wire   [31:0] grp_fu_205_p2;
reg   [31:0] tmp_37_i_reg_1025;
wire   [31:0] grp_fu_209_p2;
reg   [31:0] sum_reg_1030;
reg   [31:0] sum_reg_1030_pp0_iter26_reg;
reg   [31:0] sum_reg_1030_pp0_iter27_reg;
wire   [62:0] tmp_61_fu_269_p1;
reg   [62:0] tmp_61_reg_1036;
reg   [0:0] p_Result_7_reg_1041;
reg   [0:0] p_Result_7_reg_1041_pp0_iter27_reg;
reg   [0:0] p_Result_7_reg_1041_pp0_iter28_reg;
reg   [0:0] p_Result_7_reg_1041_pp0_iter29_reg;
reg   [10:0] exp_tmp_V_reg_1050;
wire   [51:0] tmp_63_fu_291_p1;
reg   [51:0] tmp_63_reg_1056;
wire   [53:0] p_Result_8_fu_305_p1;
reg   [53:0] p_Result_8_reg_1061;
wire   [53:0] man_V_1_fu_309_p2;
reg   [53:0] man_V_1_reg_1066;
wire   [0:0] tmp_5_i_fu_315_p2;
reg   [0:0] tmp_5_i_reg_1071;
reg   [0:0] tmp_5_i_reg_1071_pp0_iter28_reg;
reg   [0:0] tmp_5_i_reg_1071_pp0_iter29_reg;
wire   [11:0] F2_fu_320_p2;
reg   [11:0] F2_reg_1077;
wire   [0:0] tmp_7_i_fu_326_p2;
reg   [0:0] tmp_7_i_reg_1084;
reg   [0:0] tmp_7_i_reg_1084_pp0_iter28_reg;
wire  signed [11:0] F2_2_fu_338_p3;
reg  signed [11:0] F2_2_reg_1090;
reg  signed [11:0] F2_2_reg_1090_pp0_iter28_reg;
wire   [0:0] tmp_9_i_fu_346_p2;
reg   [0:0] tmp_9_i_reg_1096;
reg   [0:0] tmp_9_i_reg_1096_pp0_iter28_reg;
wire   [0:0] tmp_2_i_fu_351_p2;
reg   [0:0] tmp_2_i_reg_1103;
wire   [0:0] icmp_fu_367_p2;
reg   [0:0] icmp_reg_1108;
reg   [0:0] icmp_reg_1108_pp0_iter28_reg;
wire  signed [11:0] pos1_fu_373_p2;
reg  signed [11:0] pos1_reg_1114;
reg   [0:0] tmp_72_reg_1120;
wire   [0:0] tmp_i_i_i_i_fu_404_p2;
reg   [0:0] tmp_i_i_i_i_reg_1126;
reg   [0:0] tmp_i_i_i_i_reg_1126_pp0_iter29_reg;
wire   [0:0] tmp_i_i_i_i_100_fu_410_p2;
reg   [0:0] tmp_i_i_i_i_100_reg_1132;
reg   [0:0] tmp_i_i_i_i_100_reg_1132_pp0_iter29_reg;
wire   [7:0] tmp_65_fu_424_p1;
reg   [7:0] tmp_65_reg_1138;
wire   [0:0] p_Result_9_fu_494_p3;
reg   [0:0] p_Result_9_reg_1144;
wire   [7:0] p_Val2_15_fu_506_p2;
reg   [7:0] p_Val2_15_reg_1149;
wire   [0:0] sel_tmp2_i_fu_517_p2;
reg   [0:0] sel_tmp2_i_reg_1156;
wire   [0:0] sel_tmp3_i_fu_522_p2;
reg   [0:0] sel_tmp3_i_reg_1161;
wire   [0:0] tmp_21_i_fu_540_p2;
reg   [0:0] tmp_21_i_reg_1167;
wire   [0:0] rev1_fu_545_p2;
reg   [0:0] rev1_reg_1173;
wire   [0:0] Range1_all_ones_1_fu_570_p2;
reg   [0:0] Range1_all_ones_1_reg_1180;
reg   [0:0] tmp_74_reg_1187;
wire   [0:0] tmp_26_i_fu_584_p2;
reg   [0:0] tmp_26_i_reg_1192;
wire   [53:0] tmp_27_i_fu_590_p1;
reg   [53:0] tmp_27_i_reg_1198;
wire   [53:0] Range2_V_1_fu_594_p2;
reg   [53:0] Range2_V_1_reg_1203;
wire   [0:0] Range1_all_zeros_1_fu_606_p2;
reg   [0:0] Range1_all_zeros_1_reg_1209;
wire   [0:0] sel_tmp34_i_fu_623_p2;
reg   [0:0] sel_tmp34_i_reg_1214;
wire   [7:0] p_Val2_16_fu_694_p3;
reg   [7:0] p_Val2_16_reg_1220;
wire   [0:0] deleted_zeros_fu_817_p3;
reg   [0:0] deleted_zeros_reg_1226;
wire   [0:0] sel_tmp41_i_fu_837_p2;
reg   [0:0] sel_tmp41_i_reg_1231;
wire   [0:0] underflow_fu_857_p3;
reg   [0:0] underflow_reg_1236;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg   [10:0] t_V_reg_183;
reg    ap_block_state1;
wire    ap_CS_fsm_state34;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] grp_fu_224_p0;
wire   [31:0] grp_fu_227_p0;
wire   [63:0] d_assign_fu_230_p1;
wire   [63:0] ireg_V_fu_265_p1;
wire   [52:0] tmp_i1_fu_298_p3;
wire   [11:0] tmp_3_i_fu_295_p1;
wire   [11:0] tmp_8_i_fu_332_p2;
wire   [8:0] tmp_66_fu_357_p4;
wire   [31:0] p_Val2_12_fu_387_p1;
wire   [7:0] tmp_V_fu_390_p4;
wire   [22:0] tmp_V_3_fu_400_p1;
wire   [53:0] p_Val2_s_fu_416_p3;
wire  signed [31:0] F2_2_cast_i_fu_421_p1;
wire   [53:0] tmp_10_i_fu_428_p1;
wire   [53:0] tmp_11_i_fu_432_p2;
wire   [0:0] tmp_68_fu_442_p3;
wire   [7:0] tmp_67_fu_438_p1;
wire   [7:0] tmp_15_i_fu_450_p3;
wire   [11:0] tmp_18_i_fu_470_p2;
wire   [31:0] tmp_20_cast_i_fu_475_p1;
wire   [0:0] tmp_17_i_fu_465_p2;
wire   [0:0] p_Result_s_fu_479_p3;
wire   [7:0] p_Val2_14_fu_458_p3;
wire   [0:0] qb_fu_487_p3;
wire   [7:0] tmp_19_i_fu_502_p1;
wire   [0:0] sel_tmp1_i_fu_512_p2;
wire  signed [11:0] pos2_fu_531_p2;
wire  signed [31:0] pos1_cast_i_fu_528_p1;
wire   [53:0] tmp_23_i_fu_550_p1;
wire   [53:0] tmp_24_i_fu_554_p2;
wire   [0:0] lD_fu_560_p1;
wire   [0:0] tmp3_fu_564_p2;
wire  signed [31:0] pos2_cast_i_fu_536_p1;
wire   [0:0] tmp_26_i_not_fu_612_p2;
wire   [0:0] tmp_30_i_fu_600_p2;
wire   [0:0] sel_tmp33_i_fu_618_p2;
wire   [7:0] tmp_64_fu_629_p1;
wire   [0:0] tmp_70_fu_637_p3;
wire   [7:0] sel_tmp_i_fu_650_p3;
wire   [0:0] sel_tmp7_i_fu_662_p2;
wire   [0:0] sel_tmp8_i_fu_667_p2;
wire   [7:0] sel_tmp4_i_fu_656_p3;
wire   [0:0] sel_tmp12_demorgan_i_fu_679_p2;
wire   [0:0] sel_tmp12_i_fu_683_p2;
wire   [0:0] sel_tmp13_i_fu_689_p2;
wire   [7:0] tmp_16_i_fu_632_p2;
wire   [7:0] sel_tmp9_i_fu_672_p3;
wire   [0:0] tmp_6_not_i_fu_702_p2;
wire   [0:0] not_sel_tmp28_i_fu_707_p2;
wire   [0:0] rev_fu_644_p2;
wire   [0:0] tmp2_fu_713_p2;
wire   [0:0] rev2_fu_732_p2;
wire   [53:0] r_V_fu_742_p2;
wire   [0:0] or_cond173_i_i_i_fu_737_p2;
wire   [0:0] Range2_all_ones_fu_747_p2;
wire   [0:0] Range2_all_ones_1_i_s_fu_752_p3;
wire   [0:0] tmp_28_i_fu_769_p2;
wire   [0:0] Range1_all_zeros_fu_774_p2;
wire   [0:0] or_cond175_i_i_i_fu_760_p2;
wire   [0:0] Range1_all_ones_fu_764_p2;
wire   [0:0] sel_tmp35_i_fu_789_p3;
wire   [0:0] p_177_i_i_i_fu_785_p2;
wire   [0:0] p_180_i_i_i_fu_779_p2;
wire   [0:0] sel_tmp39_i_fu_802_p3;
wire   [0:0] carry_1_i_i_i_fu_719_p2;
wire   [0:0] Range1_all_ones_2_i_s_fu_794_p3;
wire   [0:0] Range1_all_zeros_2_i_fu_809_p3;
wire   [0:0] Range1_all_ones_2_i_fu_825_p2;
wire   [0:0] p_Result_10_fu_724_p3;
wire   [0:0] tmp4_fu_842_p2;
wire   [0:0] sel_tmp47_i_fu_853_p2;
wire   [0:0] tmp_31_i_fu_831_p2;
wire   [0:0] sel_tmp46_i_fu_848_p2;
wire   [0:0] tmp5_fu_869_p2;
wire   [0:0] p_179_demorgan_i_i_i_fu_873_p2;
wire   [0:0] underflow_not_i_fu_878_p2;
wire   [0:0] p_179_demorgan_i_i_no_fu_889_p2;
wire   [0:0] brmerge_i_i_not_i_fu_883_p2;
wire   [0:0] sel_tmp50_i_demorgan_fu_908_p2;
wire   [0:0] sel_tmp50_i_fu_912_p2;
wire   [0:0] sel_tmp51_i_fu_918_p2;
wire   [0:0] tmp_demorgan_i_fu_865_p2;
wire   [0:0] tmp_s_fu_923_p2;
wire   [0:0] tmp_37_fu_929_p2;
wire   [0:0] sel_tmp55_demorgan_i_fu_941_p2;
wire   [0:0] brmerge_i_fu_895_p2;
wire   [0:0] sel_tmp55_i_fu_946_p2;
wire   [0:0] sel_tmp56_i_fu_952_p2;
wire   [7:0] p_Val2_11_0_i_i_mux_fu_901_p3;
wire   [7:0] sel_tmp52_i_fu_934_p3;
reg    grp_fu_205_ce;
reg    grp_fu_209_ce;
reg    grp_fu_214_ce;
reg    grp_fu_219_ce;
reg    grp_fu_224_ce;
reg    grp_fu_227_ce;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
end

edge_detector_fadlbW #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
edge_detector_fadlbW_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(t1_reg_1015),
    .din1(t2_reg_1020),
    .ce(grp_fu_205_ce),
    .dout(grp_fu_205_p2)
);

edge_detector_fadlbW #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
edge_detector_fadlbW_U52(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_37_i_reg_1025),
    .din1(32'd0),
    .ce(grp_fu_209_ce),
    .dout(grp_fu_209_p2)
);

edge_detector_fmumb6 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
edge_detector_fmumb6_U53(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_i_99_reg_1005),
    .din1(32'd1056964608),
    .ce(grp_fu_214_ce),
    .dout(grp_fu_214_p2)
);

edge_detector_fmumb6 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
edge_detector_fmumb6_U54(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_36_i_reg_1010),
    .din1(32'd1056964608),
    .ce(grp_fu_219_ce),
    .dout(grp_fu_219_p2)
);

edge_detector_uitncg #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
edge_detector_uitncg_U55(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_224_p0),
    .ce(grp_fu_224_ce),
    .dout(grp_fu_224_p1)
);

edge_detector_uitncg #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
edge_detector_uitncg_U56(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_227_p0),
    .ce(grp_fu_227_ce),
    .dout(grp_fu_227_p1)
);

edge_detector_fpeocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
edge_detector_fpeocq_U57(
    .din0(sum_reg_1030),
    .dout(d_assign_fu_230_p1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((exitcond1_i_fu_233_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond1_i_fu_233_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end else if (((exitcond1_i_fu_233_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter30 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_fu_245_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_5_reg_194 <= j_V_fu_251_p2;
    end else if (((exitcond1_i_fu_233_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_5_reg_194 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        t_V_reg_183 <= i_V_reg_971;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        t_V_reg_183 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_reg_976_pp0_iter26_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        F2_2_reg_1090 <= F2_2_fu_338_p3;
        F2_reg_1077 <= F2_fu_320_p2;
        icmp_reg_1108 <= icmp_fu_367_p2;
        p_Result_8_reg_1061[51 : 0] <= p_Result_8_fu_305_p1[51 : 0];
        pos1_reg_1114 <= pos1_fu_373_p2;
        tmp_2_i_reg_1103 <= tmp_2_i_fu_351_p2;
        tmp_5_i_reg_1071 <= tmp_5_i_fu_315_p2;
        tmp_72_reg_1120 <= pos1_fu_373_p2[32'd11];
        tmp_7_i_reg_1084 <= tmp_7_i_fu_326_p2;
        tmp_9_i_reg_1096 <= tmp_9_i_fu_346_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        F2_2_reg_1090_pp0_iter28_reg <= F2_2_reg_1090;
        exitcond_i_reg_976_pp0_iter10_reg <= exitcond_i_reg_976_pp0_iter9_reg;
        exitcond_i_reg_976_pp0_iter11_reg <= exitcond_i_reg_976_pp0_iter10_reg;
        exitcond_i_reg_976_pp0_iter12_reg <= exitcond_i_reg_976_pp0_iter11_reg;
        exitcond_i_reg_976_pp0_iter13_reg <= exitcond_i_reg_976_pp0_iter12_reg;
        exitcond_i_reg_976_pp0_iter14_reg <= exitcond_i_reg_976_pp0_iter13_reg;
        exitcond_i_reg_976_pp0_iter15_reg <= exitcond_i_reg_976_pp0_iter14_reg;
        exitcond_i_reg_976_pp0_iter16_reg <= exitcond_i_reg_976_pp0_iter15_reg;
        exitcond_i_reg_976_pp0_iter17_reg <= exitcond_i_reg_976_pp0_iter16_reg;
        exitcond_i_reg_976_pp0_iter18_reg <= exitcond_i_reg_976_pp0_iter17_reg;
        exitcond_i_reg_976_pp0_iter19_reg <= exitcond_i_reg_976_pp0_iter18_reg;
        exitcond_i_reg_976_pp0_iter20_reg <= exitcond_i_reg_976_pp0_iter19_reg;
        exitcond_i_reg_976_pp0_iter21_reg <= exitcond_i_reg_976_pp0_iter20_reg;
        exitcond_i_reg_976_pp0_iter22_reg <= exitcond_i_reg_976_pp0_iter21_reg;
        exitcond_i_reg_976_pp0_iter23_reg <= exitcond_i_reg_976_pp0_iter22_reg;
        exitcond_i_reg_976_pp0_iter24_reg <= exitcond_i_reg_976_pp0_iter23_reg;
        exitcond_i_reg_976_pp0_iter25_reg <= exitcond_i_reg_976_pp0_iter24_reg;
        exitcond_i_reg_976_pp0_iter26_reg <= exitcond_i_reg_976_pp0_iter25_reg;
        exitcond_i_reg_976_pp0_iter27_reg <= exitcond_i_reg_976_pp0_iter26_reg;
        exitcond_i_reg_976_pp0_iter28_reg <= exitcond_i_reg_976_pp0_iter27_reg;
        exitcond_i_reg_976_pp0_iter29_reg <= exitcond_i_reg_976_pp0_iter28_reg;
        exitcond_i_reg_976_pp0_iter2_reg <= exitcond_i_reg_976_pp0_iter1_reg;
        exitcond_i_reg_976_pp0_iter3_reg <= exitcond_i_reg_976_pp0_iter2_reg;
        exitcond_i_reg_976_pp0_iter4_reg <= exitcond_i_reg_976_pp0_iter3_reg;
        exitcond_i_reg_976_pp0_iter5_reg <= exitcond_i_reg_976_pp0_iter4_reg;
        exitcond_i_reg_976_pp0_iter6_reg <= exitcond_i_reg_976_pp0_iter5_reg;
        exitcond_i_reg_976_pp0_iter7_reg <= exitcond_i_reg_976_pp0_iter6_reg;
        exitcond_i_reg_976_pp0_iter8_reg <= exitcond_i_reg_976_pp0_iter7_reg;
        exitcond_i_reg_976_pp0_iter9_reg <= exitcond_i_reg_976_pp0_iter8_reg;
        icmp_reg_1108_pp0_iter28_reg <= icmp_reg_1108;
        p_Result_7_reg_1041_pp0_iter27_reg <= p_Result_7_reg_1041;
        p_Result_7_reg_1041_pp0_iter28_reg <= p_Result_7_reg_1041_pp0_iter27_reg;
        p_Result_7_reg_1041_pp0_iter29_reg <= p_Result_7_reg_1041_pp0_iter28_reg;
        sum_reg_1030_pp0_iter26_reg <= sum_reg_1030;
        sum_reg_1030_pp0_iter27_reg <= sum_reg_1030_pp0_iter26_reg;
        tmp_5_i_reg_1071_pp0_iter28_reg <= tmp_5_i_reg_1071;
        tmp_5_i_reg_1071_pp0_iter29_reg <= tmp_5_i_reg_1071_pp0_iter28_reg;
        tmp_7_i_reg_1084_pp0_iter28_reg <= tmp_7_i_reg_1084;
        tmp_9_i_reg_1096_pp0_iter28_reg <= tmp_9_i_reg_1096;
        tmp_i_i_i_i_100_reg_1132_pp0_iter29_reg <= tmp_i_i_i_i_100_reg_1132;
        tmp_i_i_i_i_reg_1126_pp0_iter29_reg <= tmp_i_i_i_i_reg_1126;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_reg_976_pp0_iter27_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        Range1_all_ones_1_reg_1180 <= Range1_all_ones_1_fu_570_p2;
        Range1_all_zeros_1_reg_1209 <= Range1_all_zeros_1_fu_606_p2;
        Range2_V_1_reg_1203 <= Range2_V_1_fu_594_p2;
        p_Result_9_reg_1144 <= p_Val2_14_fu_458_p3[32'd7];
        p_Val2_15_reg_1149 <= p_Val2_15_fu_506_p2;
        rev1_reg_1173 <= rev1_fu_545_p2;
        sel_tmp2_i_reg_1156 <= sel_tmp2_i_fu_517_p2;
        sel_tmp34_i_reg_1214 <= sel_tmp34_i_fu_623_p2;
        sel_tmp3_i_reg_1161 <= sel_tmp3_i_fu_522_p2;
        tmp_21_i_reg_1167 <= tmp_21_i_fu_540_p2;
        tmp_26_i_reg_1192 <= tmp_26_i_fu_584_p2;
        tmp_27_i_reg_1198[31 : 0] <= tmp_27_i_fu_590_p1[31 : 0];
        tmp_65_reg_1138 <= tmp_65_fu_424_p1;
        tmp_74_reg_1187 <= pos2_fu_531_p2[32'd11];
        tmp_i_i_i_i_100_reg_1132 <= tmp_i_i_i_i_100_fu_410_p2;
        tmp_i_i_i_i_reg_1126 <= tmp_i_i_i_i_fu_404_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_reg_976_pp0_iter28_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        deleted_zeros_reg_1226 <= deleted_zeros_fu_817_p3;
        p_Val2_16_reg_1220 <= p_Val2_16_fu_694_p3;
        sel_tmp41_i_reg_1231 <= sel_tmp41_i_fu_837_p2;
        underflow_reg_1236 <= underflow_fu_857_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond_i_reg_976 <= exitcond_i_fu_245_p2;
        exitcond_i_reg_976_pp0_iter1_reg <= exitcond_i_reg_976;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_reg_976_pp0_iter25_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exp_tmp_V_reg_1050 <= {{ireg_V_fu_265_p1[62:52]}};
        p_Result_7_reg_1041 <= ireg_V_fu_265_p1[32'd63];
        tmp_61_reg_1036 <= tmp_61_fu_269_p1;
        tmp_63_reg_1056 <= tmp_63_fu_291_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_V_reg_971 <= i_V_fu_239_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_reg_976_pp0_iter26_reg == 1'd0) & (p_Result_7_reg_1041 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        man_V_1_reg_1066 <= man_V_1_fu_309_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_reg_976_pp0_iter24_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sum_reg_1030 <= grp_fu_209_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_reg_976_pp0_iter10_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t1_reg_1015 <= grp_fu_214_p2;
        t2_reg_1020 <= grp_fu_219_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_reg_976_pp0_iter6_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_36_i_reg_1010 <= grp_fu_227_p1;
        tmp_i_99_reg_1005 <= grp_fu_224_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_reg_976_pp0_iter17_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_37_i_reg_1025 <= grp_fu_205_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i_reg_976 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_59_reg_990 <= src2_data_stream_V_dout;
        tmp_reg_985 <= src1_data_stream_V_dout;
    end
end

always @ (*) begin
    if ((exitcond_i_fu_245_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_i_fu_233_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0) & (ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_i_fu_233_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_976_pp0_iter29_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter30 == 1'b1))) begin
        dst_data_stream_V_blk_n = dst_data_stream_V_full_n;
    end else begin
        dst_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_976_pp0_iter29_reg == 1'd0) & (ap_enable_reg_pp0_iter30 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        dst_data_stream_V_write = 1'b1;
    end else begin
        dst_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_205_ce = 1'b1;
    end else begin
        grp_fu_205_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_209_ce = 1'b1;
    end else begin
        grp_fu_209_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_214_ce = 1'b1;
    end else begin
        grp_fu_214_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_219_ce = 1'b1;
    end else begin
        grp_fu_219_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_224_ce = 1'b1;
    end else begin
        grp_fu_224_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_227_ce = 1'b1;
    end else begin
        grp_fu_227_ce = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_976 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src1_data_stream_V_blk_n = src1_data_stream_V_empty_n;
    end else begin
        src1_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_976 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src1_data_stream_V_read = 1'b1;
    end else begin
        src1_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_976 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src2_data_stream_V_blk_n = src2_data_stream_V_empty_n;
    end else begin
        src2_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_i_reg_976 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src2_data_stream_V_read = 1'b1;
    end else begin
        src2_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond1_i_fu_233_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((exitcond_i_fu_245_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter29 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter30 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter29 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter30 == 1'b1)) | ((exitcond_i_fu_245_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign F2_2_cast_i_fu_421_p1 = F2_2_reg_1090;

assign F2_2_fu_338_p3 = ((tmp_7_i_fu_326_p2[0:0] === 1'b1) ? F2_fu_320_p2 : tmp_8_i_fu_332_p2);

assign F2_fu_320_p2 = (12'd1075 - tmp_3_i_fu_295_p1);

assign Range1_all_ones_1_fu_570_p2 = (tmp_21_i_fu_540_p2 & tmp3_fu_564_p2);

assign Range1_all_ones_2_i_fu_825_p2 = (carry_1_i_i_i_fu_719_p2 & Range1_all_ones_2_i_s_fu_794_p3);

assign Range1_all_ones_2_i_s_fu_794_p3 = ((or_cond175_i_i_i_fu_760_p2[0:0] === 1'b1) ? Range1_all_ones_fu_764_p2 : sel_tmp35_i_fu_789_p3);

assign Range1_all_ones_fu_764_p2 = (Range2_all_ones_1_i_s_fu_752_p3 & Range1_all_ones_1_reg_1180);

assign Range1_all_zeros_1_fu_606_p2 = ((p_Val2_s_fu_416_p3 == 54'd0) ? 1'b1 : 1'b0);

assign Range1_all_zeros_2_i_fu_809_p3 = ((or_cond175_i_i_i_fu_760_p2[0:0] === 1'b1) ? p_180_i_i_i_fu_779_p2 : sel_tmp39_i_fu_802_p3);

assign Range1_all_zeros_fu_774_p2 = (1'd1 ^ Range1_all_ones_1_reg_1180);

assign Range2_V_1_fu_594_p2 = p_Val2_s_fu_416_p3 >> tmp_27_i_fu_590_p1;

assign Range2_all_ones_1_i_s_fu_752_p3 = ((or_cond173_i_i_i_fu_737_p2[0:0] === 1'b1) ? Range2_all_ones_fu_747_p2 : rev2_fu_732_p2);

assign Range2_all_ones_fu_747_p2 = ((Range2_V_1_reg_1203 == r_V_fu_742_p2) ? 1'b1 : 1'b0);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((exitcond_i_reg_976_pp0_iter29_reg == 1'd0) & (dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((exitcond_i_reg_976 == 1'd0) & (src2_data_stream_V_empty_n == 1'b0)) | ((exitcond_i_reg_976 == 1'd0) & (src1_data_stream_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((exitcond_i_reg_976_pp0_iter29_reg == 1'd0) & (dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((exitcond_i_reg_976 == 1'd0) & (src2_data_stream_V_empty_n == 1'b0)) | ((exitcond_i_reg_976 == 1'd0) & (src1_data_stream_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((exitcond_i_reg_976_pp0_iter29_reg == 1'd0) & (dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((exitcond_i_reg_976 == 1'd0) & (src2_data_stream_V_empty_n == 1'b0)) | ((exitcond_i_reg_976 == 1'd0) & (src1_data_stream_V_empty_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state10_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter28 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage0_iter29 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state33_pp0_stage0_iter30 = ((exitcond_i_reg_976_pp0_iter29_reg == 1'd0) & (dst_data_stream_V_full_n == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((exitcond_i_reg_976 == 1'd0) & (src2_data_stream_V_empty_n == 1'b0)) | ((exitcond_i_reg_976 == 1'd0) & (src1_data_stream_V_empty_n == 1'b0)));
end

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign brmerge_i_fu_895_p2 = (underflow_not_i_fu_878_p2 | p_179_demorgan_i_i_no_fu_889_p2);

assign brmerge_i_i_not_i_fu_883_p2 = (underflow_not_i_fu_878_p2 & p_179_demorgan_i_i_i_fu_873_p2);

assign carry_1_i_i_i_fu_719_p2 = (tmp2_fu_713_p2 & sel_tmp3_i_reg_1161);

assign deleted_zeros_fu_817_p3 = ((carry_1_i_i_i_fu_719_p2[0:0] === 1'b1) ? Range1_all_ones_2_i_s_fu_794_p3 : Range1_all_zeros_2_i_fu_809_p3);

assign dst_data_stream_V_din = ((sel_tmp56_i_fu_952_p2[0:0] === 1'b1) ? p_Val2_11_0_i_i_mux_fu_901_p3 : sel_tmp52_i_fu_934_p3);

assign exitcond1_i_fu_233_p2 = ((t_V_reg_183 == 11'd1080) ? 1'b1 : 1'b0);

assign exitcond_i_fu_245_p2 = ((t_V_5_reg_194 == 11'd1920) ? 1'b1 : 1'b0);

assign grp_fu_224_p0 = tmp_reg_985;

assign grp_fu_227_p0 = tmp_59_reg_990;

assign i_V_fu_239_p2 = (t_V_reg_183 + 11'd1);

assign icmp_fu_367_p2 = ((tmp_66_fu_357_p4 == 9'd0) ? 1'b1 : 1'b0);

assign ireg_V_fu_265_p1 = d_assign_fu_230_p1;

assign j_V_fu_251_p2 = (t_V_5_reg_194 + 11'd1);

assign lD_fu_560_p1 = tmp_24_i_fu_554_p2[0:0];

assign man_V_1_fu_309_p2 = (54'd0 - p_Result_8_fu_305_p1);

assign not_sel_tmp28_i_fu_707_p2 = (tmp_6_not_i_fu_702_p2 | sel_tmp12_demorgan_i_fu_679_p2);

assign or_cond173_i_i_i_fu_737_p2 = (tmp_26_i_reg_1192 & rev2_fu_732_p2);

assign or_cond175_i_i_i_fu_760_p2 = (tmp_26_i_reg_1192 & rev1_reg_1173);

assign p_177_i_i_i_fu_785_p2 = (rev1_reg_1173 | Range1_all_zeros_1_reg_1209);

assign p_179_demorgan_i_i_i_fu_873_p2 = (tmp5_fu_869_p2 | deleted_zeros_reg_1226);

assign p_179_demorgan_i_i_no_fu_889_p2 = (p_179_demorgan_i_i_i_fu_873_p2 ^ 1'd1);

assign p_180_i_i_i_fu_779_p2 = (tmp_28_i_fu_769_p2 & Range1_all_zeros_fu_774_p2);

assign p_Result_10_fu_724_p3 = p_Val2_16_fu_694_p3[32'd7];

assign p_Result_8_fu_305_p1 = tmp_i1_fu_298_p3;

assign p_Result_9_fu_494_p3 = p_Val2_14_fu_458_p3[32'd7];

assign p_Result_s_fu_479_p3 = p_Val2_s_fu_416_p3[tmp_20_cast_i_fu_475_p1];

assign p_Val2_11_0_i_i_mux_fu_901_p3 = ((brmerge_i_i_not_i_fu_883_p2[0:0] === 1'b1) ? p_Val2_16_reg_1220 : 8'd255);

assign p_Val2_12_fu_387_p1 = sum_reg_1030_pp0_iter27_reg;

assign p_Val2_14_fu_458_p3 = ((tmp_2_i_reg_1103[0:0] === 1'b1) ? tmp_67_fu_438_p1 : tmp_15_i_fu_450_p3);

assign p_Val2_15_fu_506_p2 = (p_Val2_14_fu_458_p3 + tmp_19_i_fu_502_p1);

assign p_Val2_16_fu_694_p3 = ((sel_tmp13_i_fu_689_p2[0:0] === 1'b1) ? tmp_16_i_fu_632_p2 : sel_tmp9_i_fu_672_p3);

assign p_Val2_s_fu_416_p3 = ((p_Result_7_reg_1041_pp0_iter27_reg[0:0] === 1'b1) ? man_V_1_reg_1066 : p_Result_8_reg_1061);

assign pos1_cast_i_fu_528_p1 = pos1_reg_1114;

assign pos1_fu_373_p2 = (12'd8 + F2_fu_320_p2);

assign pos2_cast_i_fu_536_p1 = pos2_fu_531_p2;

assign pos2_fu_531_p2 = (12'd9 + F2_reg_1077);

assign qb_fu_487_p3 = ((tmp_17_i_fu_465_p2[0:0] === 1'b1) ? p_Result_7_reg_1041_pp0_iter27_reg : p_Result_s_fu_479_p3);

assign r_V_fu_742_p2 = 54'd18014398509481983 >> tmp_27_i_reg_1198;

assign rev1_fu_545_p2 = (tmp_72_reg_1120 ^ 1'd1);

assign rev2_fu_732_p2 = (tmp_74_reg_1187 ^ 1'd1);

assign rev_fu_644_p2 = (tmp_70_fu_637_p3 ^ 1'd1);

assign sel_tmp12_demorgan_i_fu_679_p2 = (tmp_9_i_reg_1096_pp0_iter28_reg | tmp_7_i_reg_1084_pp0_iter28_reg);

assign sel_tmp12_i_fu_683_p2 = (sel_tmp12_demorgan_i_fu_679_p2 ^ 1'd1);

assign sel_tmp13_i_fu_689_p2 = (sel_tmp12_i_fu_683_p2 & icmp_reg_1108_pp0_iter28_reg);

assign sel_tmp1_i_fu_512_p2 = (tmp_9_i_reg_1096 ^ 1'd1);

assign sel_tmp2_i_fu_517_p2 = (tmp_7_i_reg_1084 & sel_tmp1_i_fu_512_p2);

assign sel_tmp33_i_fu_618_p2 = (tmp_72_reg_1120 | tmp_26_i_not_fu_612_p2);

assign sel_tmp34_i_fu_623_p2 = (tmp_30_i_fu_600_p2 & sel_tmp33_i_fu_618_p2);

assign sel_tmp35_i_fu_789_p3 = ((sel_tmp34_i_reg_1214[0:0] === 1'b1) ? Range1_all_ones_1_reg_1180 : rev1_reg_1173);

assign sel_tmp39_i_fu_802_p3 = ((sel_tmp34_i_reg_1214[0:0] === 1'b1) ? Range1_all_zeros_fu_774_p2 : p_177_i_i_i_fu_785_p2);

assign sel_tmp3_i_fu_522_p2 = (sel_tmp2_i_fu_517_p2 & p_Result_9_fu_494_p3);

assign sel_tmp41_i_fu_837_p2 = (tmp_21_i_reg_1167 ^ 1'd1);

assign sel_tmp46_i_fu_848_p2 = (tmp4_fu_842_p2 & p_Result_7_reg_1041_pp0_iter28_reg);

assign sel_tmp47_i_fu_853_p2 = (tmp_21_i_reg_1167 & p_Result_7_reg_1041_pp0_iter28_reg);

assign sel_tmp4_i_fu_656_p3 = ((sel_tmp3_i_reg_1161[0:0] === 1'b1) ? p_Val2_15_reg_1149 : sel_tmp_i_fu_650_p3);

assign sel_tmp50_i_demorgan_fu_908_p2 = (tmp_i_i_i_i_reg_1126_pp0_iter29_reg & tmp_i_i_i_i_100_reg_1132_pp0_iter29_reg);

assign sel_tmp50_i_fu_912_p2 = (sel_tmp50_i_demorgan_fu_908_p2 ^ 1'd1);

assign sel_tmp51_i_fu_918_p2 = (tmp_5_i_reg_1071_pp0_iter29_reg & sel_tmp50_i_fu_912_p2);

assign sel_tmp52_i_fu_934_p3 = ((tmp_37_fu_929_p2[0:0] === 1'b1) ? 8'd0 : p_Val2_16_reg_1220);

assign sel_tmp55_demorgan_i_fu_941_p2 = (tmp_demorgan_i_fu_865_p2 | tmp_5_i_reg_1071_pp0_iter29_reg);

assign sel_tmp55_i_fu_946_p2 = (sel_tmp55_demorgan_i_fu_941_p2 ^ 1'd1);

assign sel_tmp56_i_fu_952_p2 = (sel_tmp55_i_fu_946_p2 & brmerge_i_fu_895_p2);

assign sel_tmp7_i_fu_662_p2 = (p_Result_9_reg_1144 ^ 1'd1);

assign sel_tmp8_i_fu_667_p2 = (sel_tmp7_i_fu_662_p2 & sel_tmp2_i_reg_1156);

assign sel_tmp9_i_fu_672_p3 = ((sel_tmp8_i_fu_667_p2[0:0] === 1'b1) ? p_Val2_15_reg_1149 : sel_tmp4_i_fu_656_p3);

assign sel_tmp_i_fu_650_p3 = ((tmp_9_i_reg_1096_pp0_iter28_reg[0:0] === 1'b1) ? tmp_65_reg_1138 : 8'd0);

assign tmp2_fu_713_p2 = (rev_fu_644_p2 & not_sel_tmp28_i_fu_707_p2);

assign tmp3_fu_564_p2 = (rev1_fu_545_p2 & lD_fu_560_p1);

assign tmp4_fu_842_p2 = (sel_tmp41_i_fu_837_p2 & p_Result_10_fu_724_p3);

assign tmp5_fu_869_p2 = (sel_tmp41_i_reg_1231 | p_Result_7_reg_1041_pp0_iter29_reg);

assign tmp_10_i_fu_428_p1 = $unsigned(F2_2_cast_i_fu_421_p1);

assign tmp_11_i_fu_432_p2 = $signed(p_Val2_s_fu_416_p3) >>> tmp_10_i_fu_428_p1;

assign tmp_15_i_fu_450_p3 = ((tmp_68_fu_442_p3[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign tmp_16_i_fu_632_p2 = tmp_65_reg_1138 << tmp_64_fu_629_p1;

assign tmp_17_i_fu_465_p2 = (($signed(F2_reg_1077) > $signed(12'd54)) ? 1'b1 : 1'b0);

assign tmp_18_i_fu_470_p2 = ($signed(12'd4095) + $signed(F2_reg_1077));

assign tmp_19_i_fu_502_p1 = qb_fu_487_p3;

assign tmp_20_cast_i_fu_475_p1 = tmp_18_i_fu_470_p2;

assign tmp_21_i_fu_540_p2 = (($signed(pos1_reg_1114) < $signed(12'd54)) ? 1'b1 : 1'b0);

assign tmp_23_i_fu_550_p1 = $unsigned(pos1_cast_i_fu_528_p1);

assign tmp_24_i_fu_554_p2 = $signed(p_Val2_s_fu_416_p3) >>> tmp_23_i_fu_550_p1;

assign tmp_26_i_fu_584_p2 = (($signed(pos2_fu_531_p2) < $signed(12'd54)) ? 1'b1 : 1'b0);

assign tmp_26_i_not_fu_612_p2 = (tmp_26_i_fu_584_p2 ^ 1'd1);

assign tmp_27_i_fu_590_p1 = $unsigned(pos2_cast_i_fu_536_p1);

assign tmp_28_i_fu_769_p2 = ((Range2_V_1_reg_1203 == 54'd0) ? 1'b1 : 1'b0);

assign tmp_2_i_fu_351_p2 = ((F2_2_fu_338_p3 < 12'd54) ? 1'b1 : 1'b0);

assign tmp_30_i_fu_600_p2 = ((pos2_fu_531_p2 == 12'd54) ? 1'b1 : 1'b0);

assign tmp_31_i_fu_831_p2 = (1'd1 ^ Range1_all_ones_2_i_fu_825_p2);

assign tmp_37_fu_929_p2 = (underflow_reg_1236 | tmp_s_fu_923_p2);

assign tmp_3_i_fu_295_p1 = exp_tmp_V_reg_1050;

assign tmp_5_i_fu_315_p2 = ((tmp_61_reg_1036 == 63'd0) ? 1'b1 : 1'b0);

assign tmp_61_fu_269_p1 = ireg_V_fu_265_p1[62:0];

assign tmp_63_fu_291_p1 = ireg_V_fu_265_p1[51:0];

assign tmp_64_fu_629_p1 = F2_2_reg_1090_pp0_iter28_reg[7:0];

assign tmp_65_fu_424_p1 = p_Val2_s_fu_416_p3[7:0];

assign tmp_66_fu_357_p4 = {{F2_2_fu_338_p3[11:3]}};

assign tmp_67_fu_438_p1 = tmp_11_i_fu_432_p2[7:0];

assign tmp_68_fu_442_p3 = p_Val2_12_fu_387_p1[32'd31];

assign tmp_6_not_i_fu_702_p2 = (icmp_reg_1108_pp0_iter28_reg ^ 1'd1);

assign tmp_70_fu_637_p3 = p_Val2_15_reg_1149[32'd7];

assign tmp_7_i_fu_326_p2 = (($signed(F2_fu_320_p2) > $signed(12'd0)) ? 1'b1 : 1'b0);

assign tmp_8_i_fu_332_p2 = (12'd0 - F2_fu_320_p2);

assign tmp_9_i_fu_346_p2 = ((exp_tmp_V_reg_1050 == 11'd1075) ? 1'b1 : 1'b0);

assign tmp_V_3_fu_400_p1 = p_Val2_12_fu_387_p1[22:0];

assign tmp_V_fu_390_p4 = {{p_Val2_12_fu_387_p1[30:23]}};

assign tmp_demorgan_i_fu_865_p2 = (tmp_i_i_i_i_reg_1126_pp0_iter29_reg & tmp_i_i_i_i_100_reg_1132_pp0_iter29_reg);

assign tmp_i1_fu_298_p3 = {{1'd1}, {tmp_63_reg_1056}};

assign tmp_i_i_i_i_100_fu_410_p2 = ((tmp_V_3_fu_400_p1 != 23'd0) ? 1'b1 : 1'b0);

assign tmp_i_i_i_i_fu_404_p2 = ((tmp_V_fu_390_p4 == 8'd255) ? 1'b1 : 1'b0);

assign tmp_s_fu_923_p2 = (tmp_demorgan_i_fu_865_p2 | sel_tmp51_i_fu_918_p2);

assign underflow_fu_857_p3 = ((sel_tmp47_i_fu_853_p2[0:0] === 1'b1) ? tmp_31_i_fu_831_p2 : sel_tmp46_i_fu_848_p2);

assign underflow_not_i_fu_878_p2 = (underflow_reg_1236 ^ 1'd1);

always @ (posedge ap_clk) begin
    p_Result_8_reg_1061[53:52] <= 2'b01;
    tmp_27_i_reg_1198[53:32] <= 22'b0000000000000000000000;
end

endmodule //AddWeighted
